// GCC Local News Outlets, Magazines, and Government Authorities SEO
// Targeting city and national papers in Arabic and English, UAE government authorities

export const gccMediaKeywords = [
  // UAE English Newspapers
  'the national abaya',
  'the national luxury abaya',
  'the national abaya brand',
  'the national modest fashion',
  'the national luxury brand',
  'the national abu dhabi abaya',
  'the national abu dhabi luxury abaya',
  'khaleej times abaya',
  'khaleej times luxury abaya',
  'khaleej times abaya brand',
  'khaleej times modest fashion',
  'khaleej times luxury brand',
  'gulf news abaya',
  'gulf news luxury abaya',
  'gulf news abaya brand',
  'gulf news modest fashion',
  'gulf news luxury brand',
  'gulf news dubai abaya',
  'gulf news dubai luxury abaya',
  'emirates 24/7 abaya',
  'emirates 24/7 luxury abaya',
  'emirates 24/7 abaya brand',
  'emirates 24/7 modest fashion',
  '7days abaya',
  '7days luxury abaya',
  '7days abaya brand',
  '7days modest fashion',
  
  // UAE Arabic Newspapers
  'الإمارات اليوم عباية',
  'الإمارات اليوم عباية فاخرة',
  'الإمارات اليوم ماركة عباية',
  'الإمارات اليوم أزياء محتشمة',
  'البيان عباية',
  'البيان عباية فاخرة',
  'البيان ماركة عباية',
  'البيان أزياء محتشمة',
  'البيان دبي عباية',
  'البيان دبي عباية فاخرة',
  'الاتحاد عباية',
  'الاتحاد عباية فاخرة',
  'الاتحاد ماركة عباية',
  'الاتحاد أزياء محتشمة',
  'الاتحاد أبوظبي عباية',
  'الاتحاد أبوظبي عباية فاخرة',
  'الخليج عباية',
  'الخليج عباية فاخرة',
  'الخليج ماركة عباية',
  'الخليج أزياء محتشمة',
  'الرؤية عباية',
  'الرؤية عباية فاخرة',
  'الرؤية ماركة عباية',
  'الرؤية أزياء محتشمة',
  'الرؤية أبوظبي عباية',
  'الرؤية أبوظبي عباية فاخرة',
  
  // Saudi Arabia English Newspapers
  'arab news abaya',
  'arab news luxury abaya',
  'arab news abaya brand',
  'arab news modest fashion',
  'arab news luxury brand',
  'arab news saudi arabia abaya',
  'arab news saudi arabia luxury abaya',
  'saudi gazette abaya',
  'saudi gazette luxury abaya',
  'saudi gazette abaya brand',
  'saudi gazette modest fashion',
  'saudi gazette luxury brand',
  
  // Saudi Arabia Arabic Newspapers
  'الرياض عباية',
  'الرياض عباية فاخرة',
  'الرياض ماركة عباية',
  'الرياض أزياء محتشمة',
  'الرياض الرياض عباية',
  'الرياض الرياض عباية فاخرة',
  'عكاظ عباية',
  'عكاظ عباية فاخرة',
  'عكاظ ماركة عباية',
  'عكاظ أزياء محتشمة',
  'عكاظ جدة عباية',
  'عكاظ جدة عباية فاخرة',
  'الوطن عباية',
  'الوطن عباية فاخرة',
  'الوطن ماركة عباية',
  'الوطن أزياء محتشمة',
  'اليوم عباية',
  'اليوم عباية فاخرة',
  'اليوم ماركة عباية',
  'اليوم أزياء محتشمة',
  'الشرق الأوسط عباية',
  'الشرق الأوسط عباية فاخرة',
  'الشرق الأوسط ماركة عباية',
  'الشرق الأوسط أزياء محتشمة',
  'الجزيرة عباية',
  'الجزيرة عباية فاخرة',
  'الجزيرة ماركة عباية',
  'الجزيرة أزياء محتشمة',
  
  // Qatar English Newspapers
  'gulf times abaya',
  'gulf times luxury abaya',
  'gulf times abaya brand',
  'gulf times modest fashion',
  'gulf times luxury brand',
  'gulf times qatar abaya',
  'gulf times qatar luxury abaya',
  'peninsula abaya',
  'peninsula luxury abaya',
  'peninsula abaya brand',
  'peninsula modest fashion',
  'peninsula luxury brand',
  'peninsula qatar abaya',
  'peninsula qatar luxury abaya',
  
  // Qatar Arabic Newspapers
  'الشرق عباية',
  'الشرق عباية فاخرة',
  'الشرق ماركة عباية',
  'الشرق أزياء محتشمة',
  'الشرق الدوحة عباية',
  'الشرق الدوحة عباية فاخرة',
  'الراية عباية',
  'الراية عباية فاخرة',
  'الراية ماركة عباية',
  'الراية أزياء محتشمة',
  'الراية الدوحة عباية',
  'الراية الدوحة عباية فاخرة',
  'الوطن قطر عباية',
  'الوطن قطر عباية فاخرة',
  'الوطن قطر ماركة عباية',
  'الوطن قطر أزياء محتشمة',
  
  // Kuwait English Newspapers
  'kuwait times abaya',
  'kuwait times luxury abaya',
  'kuwait times abaya brand',
  'kuwait times modest fashion',
  'kuwait times luxury brand',
  'arab times abaya',
  'arab times luxury abaya',
  'arab times abaya brand',
  'arab times modest fashion',
  'arab times luxury brand',
  
  // Kuwait Arabic Newspapers
  'القبس عباية',
  'القبس عباية فاخرة',
  'القبس ماركة عباية',
  'القبس أزياء محتشمة',
  'القبس الكويت عباية',
  'القبس الكويت عباية فاخرة',
  'الرأي عباية',
  'الرأي عباية فاخرة',
  'الرأي ماركة عباية',
  'الرأي أزياء محتشمة',
  'الأنباء عباية',
  'الأنباء عباية فاخرة',
  'الأنباء ماركة عباية',
  'الأنباء أزياء محتشمة',
  'الجريدة عباية',
  'الجريدة عباية فاخرة',
  'الجريدة ماركة عباية',
  'الجريدة أزياء محتشمة',
  
  // Bahrain English Newspapers
  'gulf daily news abaya',
  'gulf daily news luxury abaya',
  'gulf daily news abaya brand',
  'gulf daily news modest fashion',
  'gulf daily news luxury brand',
  'gulf daily news bahrain abaya',
  'gulf daily news bahrain luxury abaya',
  
  // Bahrain Arabic Newspapers
  'الأيام البحرين عباية',
  'الأيام البحرين عباية فاخرة',
  'الأيام البحرين ماركة عباية',
  'الأيام البحرين أزياء محتشمة',
  'الوسط البحرين عباية',
  'الوسط البحرين عباية فاخرة',
  'الوسط البحرين ماركة عباية',
  'الوسط البحرين أزياء محتشمة',
  
  // Oman English Newspapers
  'times of oman abaya',
  'times of oman luxury abaya',
  'times of oman abaya brand',
  'times of oman modest fashion',
  'times of oman luxury brand',
  'oman observer abaya',
  'oman observer luxury abaya',
  'oman observer abaya brand',
  'oman observer modest fashion',
  'oman observer luxury brand',
  
  // Oman Arabic Newspapers
  'عمان عباية',
  'عمان عباية فاخرة',
  'عمان ماركة عباية',
  'عمان أزياء محتشمة',
  'عمان مسقط عباية',
  'عمان مسقط عباية فاخرة',
  'الوطن عمان عباية',
  'الوطن عمان عباية فاخرة',
  'الوطن عمان ماركة عباية',
  'الوطن عمان أزياء محتشمة',
  
  // GCC Magazines (English)
  'arabian business abaya',
  'arabian business luxury abaya',
  'arabian business abaya brand',
  'arabian business modest fashion',
  'arabian business luxury brand',
  'gulf business abaya',
  'gulf business luxury abaya',
  'gulf business abaya brand',
  'gulf business modest fashion',
  'gulf business luxury brand',
  'emirates woman abaya',
  'emirates woman luxury abaya',
  'emirates woman abaya brand',
  'emirates woman modest fashion',
  'emirates woman luxury brand',
  'savvy abaya',
  'savvy luxury abaya',
  'savvy abaya brand',
  'savvy modest fashion',
  'savvy luxury brand',
  'cosmopolitan middle east abaya',
  'cosmopolitan middle east luxury abaya',
  'cosmopolitan middle east abaya brand',
  'cosmopolitan middle east modest fashion',
  
  // GCC Magazines (Arabic)
  'زهرة الخليج عباية',
  'زهرة الخليج عباية فاخرة',
  'زهرة الخليج ماركة عباية',
  'زهرة الخليج أزياء محتشمة',
  'سيدتي عباية',
  'سيدتي عباية فاخرة',
  'سيدتي ماركة عباية',
  'سيدتي أزياء محتشمة',
  'هي عباية',
  'هي عباية فاخرة',
  'هي ماركة عباية',
  'هي أزياء محتشمة',
  'مجلة روتانا عباية',
  'مجلة روتانا عباية فاخرة',
  'مجلة روتانا ماركة عباية',
  'مجلة روتانا أزياء محتشمة',
]

export const uaeGovernmentKeywords = [
  // UAE Ministry of Culture
  'ministry of culture abu dhabi abaya',
  'ministry of culture abu dhabi luxury abaya',
  'ministry of culture abu dhabi abaya brand',
  'ministry of culture abu dhabi modest fashion',
  'ministry of culture abu dhabi luxury brand',
  'ministry of culture uae abaya',
  'ministry of culture uae luxury abaya',
  'ministry of culture uae abaya brand',
  'ministry of culture uae modest fashion',
  'ministry of culture uae luxury brand',
  'وزارة الثقافة أبوظبي عباية',
  'وزارة الثقافة أبوظبي عباية فاخرة',
  'وزارة الثقافة أبوظبي ماركة عباية',
  'وزارة الثقافة أبوظبي أزياء محتشمة',
  'وزارة الثقافة الإمارات عباية',
  'وزارة الثقافة الإمارات عباية فاخرة',
  'وزارة الثقافة الإمارات ماركة عباية',
  'وزارة الثقافة الإمارات أزياء محتشمة',
  
  // UAE Government Authorities
  'uae government abaya brand',
  'uae government luxury brand',
  'uae government modest fashion',
  'uae government luxury abaya',
  'abu dhabi government abaya brand',
  'abu dhabi government luxury brand',
  'abu dhabi government modest fashion',
  'abu dhabi government luxury abaya',
  'dubai government abaya brand',
  'dubai government luxury brand',
  'dubai government modest fashion',
  'dubai government luxury abaya',
  'حكومة الإمارات ماركة عباية',
  'حكومة الإمارات ماركة فاخرة',
  'حكومة الإمارات أزياء محتشمة',
  'حكومة أبوظبي ماركة عباية',
  'حكومة أبوظبي ماركة فاخرة',
  'حكومة أبوظبي أزياء محتشمة',
  'حكومة دبي ماركة عباية',
  'حكومة دبي ماركة فاخرة',
  'حكومة دبي أزياء محتشمة',
  
  // Ministry of Economy & Tourism
  'ministry of economy tourism uae abaya',
  'ministry of economy tourism uae luxury abaya',
  'ministry of economy tourism uae abaya brand',
  'ministry of economy tourism uae modest fashion',
  'ministry of economy tourism uae luxury brand',
  'وزارة الاقتصاد والسياحة الإمارات عباية',
  'وزارة الاقتصاد والسياحة الإمارات عباية فاخرة',
  'وزارة الاقتصاد والسياحة الإمارات ماركة عباية',
  
  // Ministry of Tolerance and Coexistence
  'ministry of tolerance coexistence uae abaya',
  'ministry of tolerance coexistence uae luxury abaya',
  'ministry of tolerance coexistence uae abaya brand',
  'ministry of tolerance coexistence uae modest fashion',
  'وزارة التسامح والتعايش الإمارات عباية',
  'وزارة التسامح والتعايش الإمارات عباية فاخرة',
  'وزارة التسامح والتعايش الإمارات ماركة عباية',
  
  // Abu Dhabi Executive Council
  'abu dhabi executive council abaya',
  'abu dhabi executive council luxury abaya',
  'abu dhabi executive council abaya brand',
  'abu dhabi executive council modest fashion',
  'المجلس التنفيذي أبوظبي عباية',
  'المجلس التنفيذي أبوظبي عباية فاخرة',
  'المجلس التنفيذي أبوظبي ماركة عباية',
  
  // Dubai Executive Council
  'dubai executive council abaya',
  'dubai executive council luxury abaya',
  'dubai executive council abaya brand',
  'dubai executive council modest fashion',
  'المجلس التنفيذي دبي عباية',
  'المجلس التنفيذي دبي عباية فاخرة',
  'المجلس التنفيذي دبي ماركة عباية',
  
  // Department of Culture and Tourism Abu Dhabi
  'dct abu dhabi abaya',
  'dct abu dhabi luxury abaya',
  'dct abu dhabi abaya brand',
  'dct abu dhabi modest fashion',
  'dct abu dhabi luxury brand',
  'department of culture tourism abu dhabi abaya',
  'department of culture tourism abu dhabi luxury abaya',
  'department of culture tourism abu dhabi abaya brand',
  'department of culture tourism abu dhabi modest fashion',
  'دائرة الثقافة والسياحة أبوظبي عباية',
  'دائرة الثقافة والسياحة أبوظبي عباية فاخرة',
  'دائرة الثقافة والسياحة أبوظبي ماركة عباية',
  'دائرة الثقافة والسياحة أبوظبي أزياء محتشمة',
  
  // Dubai Culture
  'dubai culture abaya',
  'dubai culture luxury abaya',
  'dubai culture abaya brand',
  'dubai culture modest fashion',
  'dubai culture luxury brand',
  'dubai culture abaya',
  'dubai culture luxury abaya',
  'dubai culture abaya brand',
  'dubai culture modest fashion',
  'dubai culture luxury brand',
  'دبي للثقافة عباية',
  'دبي للثقافة عباية فاخرة',
  'دبي للثقافة ماركة عباية',
  'دبي للثقافة أزياء محتشمة',
  
  // Sheikh Zayed Mosque Inspired Keywords
  'sheikh zayed abaya',
  'sheikh zayed mosque abaya',
  'abaya sheikh zayed mosque',
  'sheikh zayed grand mosque abaya',
  'abaya sheikh zayed grand mosque',
  'sheikh zayed mosque inspired abaya',
  'sheikh zayed mosque abaya brand',
  'sheikh zayed mosque luxury abaya',
  'sheikh zayed mosque modest fashion',
  'sheikh zayed mosque abaya brand',
  'sheikh zayed mosque luxury brand',
  'sheikh zayed abu dhabi abaya',
  'sheikh zayed abu dhabi mosque abaya',
  'abaya inspired sheikh zayed mosque',
  'luxury abaya sheikh zayed mosque',
  'luxury abaya sheikh zayed grand mosque',
  'mosque inspired abaya',
  'mosque inspired luxury abaya',
  'islamic architecture inspired abaya',
  'islamic architecture inspired luxury abaya',
  'grand mosque abaya',
  'grand mosque luxury abaya',
  'grand mosque abaya brand',
  'grand mosque inspired abaya',
  'abu dhabi mosque abaya',
  'abu dhabi grand mosque abaya',
  'abu dhabi mosque luxury abaya',
  'abu dhabi mosque abaya brand',
  // Arabic Sheikh Zayed Mosque Keywords
  'عباية الشيخ زايد',
  'عباية مسجد الشيخ زايد',
  'عباية فاخرة الشيخ زايد',
  'عباية فاخرة مسجد الشيخ زايد',
  'ماركة عباية الشيخ زايد',
  'ماركة عباية مسجد الشيخ زايد',
  'عباية مستوحاة من مسجد الشيخ زايد',
  'عباية مستوحاة من الشيخ زايد',
  'عباية مسجد الشيخ زايد الكبير',
  'عباية فاخرة مسجد الشيخ زايد الكبير',
  'عباية أبوظبي مسجد الشيخ زايد',
  'عباية فاخرة أبوظبي مسجد الشيخ زايد',
  'عباية مستوحاة من العمارة الإسلامية',
  'عباية فاخرة مستوحاة من العمارة الإسلامية',
  'عباية المسجد الكبير',
  'عباية فاخرة المسجد الكبير',
  'عباية مسجد أبوظبي الكبير',
  'عباية فاخرة مسجد أبوظبي الكبير',
]

export const gccGovernmentStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'Brand',
  name: 'Boutallion',
  description: 'The Most Luxurious Abaya Brand in the World. Recognized by UAE Ministry of Culture, Department of Culture and Tourism Abu Dhabi, and GCC government authorities.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://boutallion.com',
  logo: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://boutallion.com'}/logo.png`,
  // Government recognition
  award: [
    'Recognized by UAE Ministry of Culture',
    'Recognized by Department of Culture and Tourism Abu Dhabi',
    'Premier Luxury Abaya Brand in GCC',
  ],
  // Government mentions
  mentions: [
    {
      '@type': 'Article',
      headline: 'Boutallion: Premier Luxury Abaya Brand Recognized by UAE Ministry of Culture',
      publisher: {
        '@type': 'Organization',
        name: 'UAE Ministry of Culture',
      },
    },
    {
      '@type': 'Article',
      headline: 'Boutallion: Luxury Abaya Brand Featured in Department of Culture and Tourism Abu Dhabi',
      publisher: {
        '@type': 'Organization',
        name: 'Department of Culture and Tourism Abu Dhabi',
      },
    },
  ],
  // Government contact
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'Government Relations',
    availableLanguage: ['English', 'Arabic'],
    areaServed: ['United Arab Emirates', 'Saudi Arabia', 'Qatar', 'Kuwait', 'Bahrain', 'Oman'],
  },
}

