// Press and Media SEO Optimization
// Targeting fashion magazines, luxury publications, and press mentions

export const pressKeywords = [
  // Fashion Magazine Keywords - All Editions
  'vogue abaya',
  'vogue abaya brand',
  'vogue luxury abaya',
  'vogue modest fashion',
  // Vogue Regional Editions
  'vogue arabia abaya',
  'vogue arabia luxury abaya',
  'vogue arabia modest fashion',
  'vogue arabia abaya brand',
  'vogue italia abaya',
  'vogue italia luxury abaya',
  'vogue italia alta moda',
  'vogue italia modest fashion',
  'vogue italia abaya brand',
  'vogue france abaya',
  'vogue france luxury abaya',
  'vogue france modest fashion',
  'vogue uk abaya',
  'vogue uk luxury abaya',
  'vogue uk modest fashion',
  'vogue us abaya',
  'vogue us luxury abaya',
  'vogue us modest fashion',
  'vogue mexico abaya',
  'vogue mexico luxury abaya',
  'vogue mexico modest fashion',
  'vogue spain abaya',
  'vogue spain luxury abaya',
  'vogue spain modest fashion',
  'vogue germany abaya',
  'vogue germany luxury abaya',
  'vogue germany modest fashion',
  'vogue japan abaya',
  'vogue japan luxury abaya',
  'vogue japan modest fashion',
  'vogue china abaya',
  'vogue china luxury abaya',
  'vogue china modest fashion',
  'vogue india abaya',
  'vogue india luxury abaya',
  'vogue india modest fashion',
  'vogue russia abaya',
  'vogue russia luxury abaya',
  'vogue russia modest fashion',
  'vogue australia abaya',
  'vogue australia luxury abaya',
  'vogue australia modest fashion',
  'vogue brazil abaya',
  'vogue brazil luxury abaya',
  'vogue brazil modest fashion',
  // Marie Claire Regional Editions
  'marie claire abaya',
  'marie claire luxury abaya',
  'marie claire modest fashion',
  'marie claire abaya brand',
  'marie claire arabia abaya',
  'marie claire arabia luxury abaya',
  'marie claire arabia modest fashion',
  'marie claire arabia abaya brand',
  'marie claire middle east abaya',
  'marie claire middle east luxury abaya',
  'marie claire middle east modest fashion',
  'marie claire middle east abaya brand',
  'marie claire italia abaya',
  'marie claire italia luxury abaya',
  'marie claire italia modest fashion',
  'marie claire italia abaya brand',
  'marie claire france abaya',
  'marie claire france luxury abaya',
  'marie claire france modest fashion',
  'marie claire france abaya brand',
  'marie claire uk abaya',
  'marie claire uk luxury abaya',
  'marie claire uk modest fashion',
  'marie claire uk abaya brand',
  'marie claire us abaya',
  'marie claire us luxury abaya',
  'marie claire us modest fashion',
  'marie claire us abaya brand',
  'marie claire spain abaya',
  'marie claire spain luxury abaya',
  'marie claire spain modest fashion',
  'marie claire spain abaya brand',
  'marie claire germany abaya',
  'marie claire germany luxury abaya',
  'marie claire germany modest fashion',
  'marie claire germany abaya brand',
  'marie claire mexico abaya',
  'marie claire mexico luxury abaya',
  'marie claire mexico modest fashion',
  'marie claire mexico abaya brand',
  'marie claire australia abaya',
  'marie claire australia luxury abaya',
  'marie claire australia modest fashion',
  'marie claire australia abaya brand',
  // Elle Regional Editions
  'elle abaya',
  'elle luxury abaya',
  'elle modest fashion',
  'elle abaya brand',
  'elle arabia abaya',
  'elle arabia luxury abaya',
  'elle arabia modest fashion',
  'elle arabia abaya brand',
  'elle middle east abaya',
  'elle middle east luxury abaya',
  'elle middle east modest fashion',
  'elle middle east abaya brand',
  'elle italia abaya',
  'elle italia luxury abaya',
  'elle italia modest fashion',
  'elle italia abaya brand',
  'elle france abaya',
  'elle france luxury abaya',
  'elle france modest fashion',
  'elle france abaya brand',
  'elle uk abaya',
  'elle uk luxury abaya',
  'elle uk modest fashion',
  'elle uk abaya brand',
  'elle us abaya',
  'elle us luxury abaya',
  'elle us modest fashion',
  'elle us abaya brand',
  'elle spain abaya',
  'elle spain luxury abaya',
  'elle spain modest fashion',
  'elle spain abaya brand',
  'elle germany abaya',
  'elle germany luxury abaya',
  'elle germany modest fashion',
  'elle germany abaya brand',
  'elle mexico abaya',
  'elle mexico luxury abaya',
  'elle mexico modest fashion',
  'elle mexico abaya brand',
  'elle australia abaya',
  'elle australia luxury abaya',
  'elle australia modest fashion',
  'elle australia abaya brand',
  'elle japan abaya',
  'elle japan luxury abaya',
  'elle japan modest fashion',
  'elle japan abaya brand',
  'elle china abaya',
  'elle china luxury abaya',
  'elle china modest fashion',
  'elle china abaya brand',
  'elle india abaya',
  'elle india luxury abaya',
  'elle india modest fashion',
  'elle india abaya brand',
  'elle russia abaya',
  'elle russia luxury abaya',
  'elle russia modest fashion',
  'elle russia abaya brand',
  'elle brazil abaya',
  'elle brazil luxury abaya',
  'elle brazil modest fashion',
  'elle brazil abaya brand',
  'harper\'s bazaar abaya',
  'harpers bazaar abaya',
  'harper\'s bazaar luxury abaya',
  'harper\'s bazaar modest fashion',
  // Cosmopolitan Regional Editions
  'cosmopolitan abaya',
  'cosmopolitan luxury abaya',
  'cosmopolitan modest fashion',
  'cosmopolitan abaya brand',
  'cosmopolitan arabia abaya',
  'cosmopolitan arabia luxury abaya',
  'cosmopolitan arabia modest fashion',
  'cosmopolitan arabia abaya brand',
  'cosmopolitan middle east abaya',
  'cosmopolitan middle east luxury abaya',
  'cosmopolitan middle east modest fashion',
  'cosmopolitan middle east abaya brand',
  'cosmopolitan uk abaya',
  'cosmopolitan uk luxury abaya',
  'cosmopolitan uk modest fashion',
  'cosmopolitan uk abaya brand',
  'cosmopolitan us abaya',
  'cosmopolitan us luxury abaya',
  'cosmopolitan us modest fashion',
  'cosmopolitan us abaya brand',
  'cosmopolitan italia abaya',
  'cosmopolitan italia luxury abaya',
  'cosmopolitan italia modest fashion',
  'cosmopolitan italia abaya brand',
  'cosmopolitan france abaya',
  'cosmopolitan france luxury abaya',
  'cosmopolitan france modest fashion',
  'cosmopolitan france abaya brand',
  'cosmopolitan spain abaya',
  'cosmopolitan spain luxury abaya',
  'cosmopolitan spain modest fashion',
  'cosmopolitan spain abaya brand',
  'cosmopolitan germany abaya',
  'cosmopolitan germany luxury abaya',
  'cosmopolitan germany modest fashion',
  'cosmopolitan germany abaya brand',
  'cosmopolitan australia abaya',
  'cosmopolitan australia luxury abaya',
  'cosmopolitan australia modest fashion',
  'cosmopolitan australia abaya brand',
  'cosmopolitan mexico abaya',
  'cosmopolitan mexico luxury abaya',
  'cosmopolitan mexico modest fashion',
  'cosmopolitan mexico abaya brand',
  'cosmopolitan japan abaya',
  'cosmopolitan japan luxury abaya',
  'cosmopolitan japan modest fashion',
  'cosmopolitan japan abaya brand',
  'cosmopolitan india abaya',
  'cosmopolitan india luxury abaya',
  'cosmopolitan india modest fashion',
  'cosmopolitan india abaya brand',
  'cosmopolitan russia abaya',
  'cosmopolitan russia luxury abaya',
  'cosmopolitan russia modest fashion',
  'cosmopolitan russia abaya brand',
  'cosmopolitan brazil abaya',
  'cosmopolitan brazil luxury abaya',
  'cosmopolitan brazil modest fashion',
  'cosmopolitan brazil abaya brand',
  // Vanity Fair Regional Editions
  'vanity fair abaya',
  'vanity fair luxury abaya',
  'vanity fair modest fashion',
  'vanity fair abaya brand',
  'vanity fair italia abaya',
  'vanity fair italia luxury abaya',
  'vanity fair italia modest fashion',
  'vanity fair italia abaya brand',
  'vanity fair uk abaya',
  'vanity fair uk luxury abaya',
  'vanity fair uk modest fashion',
  'vanity fair uk abaya brand',
  'vanity fair us abaya',
  'vanity fair us luxury abaya',
  'vanity fair us modest fashion',
  'vanity fair us abaya brand',
  'vanity fair france abaya',
  'vanity fair france luxury abaya',
  'vanity fair france modest fashion',
  'vanity fair france abaya brand',
  'vanity fair spain abaya',
  'vanity fair spain luxury abaya',
  'vanity fair spain modest fashion',
  'vanity fair spain abaya brand',
  'vanity fair germany abaya',
  'vanity fair germany luxury abaya',
  'vanity fair germany modest fashion',
  'vanity fair germany abaya brand',
  // W Magazine Regional Editions
  'w magazine abaya',
  'w magazine luxury abaya',
  'w magazine modest fashion',
  'w magazine abaya brand',
  'w magazine us abaya',
  'w magazine us luxury abaya',
  'w magazine us modest fashion',
  'w magazine us abaya brand',
  'w magazine uk abaya',
  'w magazine uk luxury abaya',
  'w magazine uk modest fashion',
  'w magazine uk abaya brand',
  'w magazine italia abaya',
  'w magazine italia luxury abaya',
  'w magazine italia modest fashion',
  'w magazine italia abaya brand',
  'w magazine france abaya',
  'w magazine france luxury abaya',
  'w magazine france modest fashion',
  'w magazine france abaya brand',
  'w magazine spain abaya',
  'w magazine spain luxury abaya',
  'w magazine spain modest fashion',
  'w magazine spain abaya brand',
  'w magazine germany abaya',
  'w magazine germany luxury abaya',
  'w magazine germany modest fashion',
  'w magazine germany abaya brand',
  // Bazaar Regional Editions
  'bazaar abaya',
  'bazaar luxury abaya',
  'bazaar modest fashion',
  'bazaar abaya brand',
  'bazaar arabia abaya',
  'bazaar arabia luxury abaya',
  'bazaar arabia modest fashion',
  'bazaar arabia abaya brand',
  'bazaar middle east abaya',
  'bazaar middle east luxury abaya',
  'bazaar middle east modest fashion',
  'bazaar middle east abaya brand',
  'bazaar italia abaya',
  'bazaar italia luxury abaya',
  'bazaar italia modest fashion',
  'bazaar italia abaya brand',
  'bazaar uk abaya',
  'bazaar uk luxury abaya',
  'bazaar uk modest fashion',
  'bazaar uk abaya brand',
  'bazaar us abaya',
  'bazaar us luxury abaya',
  'bazaar us modest fashion',
  'bazaar us abaya brand',
  'bazaar spain abaya',
  'bazaar spain luxury abaya',
  'bazaar spain modest fashion',
  'bazaar spain abaya brand',
  'bazaar germany abaya',
  'bazaar germany luxury abaya',
  'bazaar germany modest fashion',
  'bazaar germany abaya brand',
  'bazaar australia abaya',
  'bazaar australia luxury abaya',
  'bazaar australia modest fashion',
  'bazaar australia abaya brand',
  'bazaar japan abaya',
  'bazaar japan luxury abaya',
  'bazaar japan modest fashion',
  'bazaar japan abaya brand',
  'bazaar china abaya',
  'bazaar china luxury abaya',
  'bazaar china modest fashion',
  'bazaar china abaya brand',
  'bazaar india abaya',
  'bazaar india luxury abaya',
  'bazaar india modest fashion',
  'bazaar india abaya brand',
  'bazaar russia abaya',
  'bazaar russia luxury abaya',
  'bazaar russia modest fashion',
  'bazaar russia abaya brand',
  'bazaar brazil abaya',
  'bazaar brazil luxury abaya',
  'bazaar brazil modest fashion',
  'bazaar brazil abaya brand',
  
  // Forbes Regional Editions
  'forbes luxury brand',
  'forbes luxury abaya brand',
  'forbes most luxurious abaya brand',
  'forbes modest fashion',
  'forbes luxury fashion brand',
  'forbes abaya brand',
  'forbes middle east abaya',
  'forbes middle east luxury abaya',
  'forbes middle east luxury brand',
  'forbes middle east abaya brand',
  'forbes middle east modest fashion',
  'forbes middle east luxury fashion brand',
  'forbes arabia abaya',
  'forbes arabia luxury abaya',
  'forbes arabia luxury brand',
  'forbes arabia abaya brand',
  'forbes arabia modest fashion',
  'forbes arabia luxury fashion brand',
  'forbes italia abaya',
  'forbes italia luxury abaya',
  'forbes italia luxury brand',
  'forbes italia abaya brand',
  'forbes italia modest fashion',
  'forbes italia luxury fashion brand',
  'forbes france abaya',
  'forbes france luxury abaya',
  'forbes france luxury brand',
  'forbes france abaya brand',
  'forbes france modest fashion',
  'forbes france luxury fashion brand',
  'forbes uk abaya',
  'forbes uk luxury abaya',
  'forbes uk luxury brand',
  'forbes uk abaya brand',
  'forbes uk modest fashion',
  'forbes uk luxury fashion brand',
  'forbes us abaya',
  'forbes us luxury abaya',
  'forbes us luxury brand',
  'forbes us abaya brand',
  'forbes us modest fashion',
  'forbes us luxury fashion brand',
  'forbes spain abaya',
  'forbes spain luxury abaya',
  'forbes spain luxury brand',
  'forbes spain abaya brand',
  'forbes spain modest fashion',
  'forbes spain luxury fashion brand',
  'forbes germany abaya',
  'forbes germany luxury abaya',
  'forbes germany luxury brand',
  'forbes germany abaya brand',
  'forbes germany modest fashion',
  'forbes germany luxury fashion brand',
  'forbes japan abaya',
  'forbes japan luxury abaya',
  'forbes japan luxury brand',
  'forbes japan abaya brand',
  'forbes japan modest fashion',
  'forbes japan luxury fashion brand',
  'forbes china abaya',
  'forbes china luxury abaya',
  'forbes china luxury brand',
  'forbes china abaya brand',
  'forbes china modest fashion',
  'forbes china luxury fashion brand',
  'forbes india abaya',
  'forbes india luxury abaya',
  'forbes india luxury brand',
  'forbes india abaya brand',
  'forbes india modest fashion',
  'forbes india luxury fashion brand',
  'forbes russia abaya',
  'forbes russia luxury abaya',
  'forbes russia luxury brand',
  'forbes russia abaya brand',
  'forbes russia modest fashion',
  'forbes russia luxury fashion brand',
  'forbes australia abaya',
  'forbes australia luxury abaya',
  'forbes australia luxury brand',
  'forbes australia abaya brand',
  'forbes australia modest fashion',
  'forbes australia luxury fashion brand',
  'forbes brazil abaya',
  'forbes brazil luxury abaya',
  'forbes brazil luxury brand',
  'forbes brazil abaya brand',
  'forbes brazil modest fashion',
  'forbes brazil luxury fashion brand',
  'forbes mexico abaya',
  'forbes mexico luxury abaya',
  'forbes mexico luxury brand',
  'forbes mexico abaya brand',
  'forbes mexico modest fashion',
  'forbes mexico luxury fashion brand',
  // Other Luxury Publications
  'financial times luxury brand',
  'financial times luxury abaya',
  'financial times abaya brand',
  'financial times modest fashion',
  'wall street journal luxury brand',
  'wall street journal luxury abaya',
  'wall street journal abaya brand',
  'wall street journal modest fashion',
  'the new york times luxury abaya',
  'the new york times modest fashion',
  'the new york times abaya brand',
  'the new york times luxury brand',
  'the guardian luxury abaya',
  'the guardian modest fashion',
  'the guardian abaya brand',
  'the guardian luxury brand',
  
  // Press Mentions
  'most luxurious abaya brand ever',
  'most luxurious modest fashion brand',
  'most luxurious abaya brand in the world',
  'world\'s most luxurious abaya brand',
  'world\'s most luxurious modest fashion brand',
  'most expensive abaya brand',
  'most exclusive abaya brand',
  'most prestigious abaya brand',
  'most prestigious modest fashion brand',
  'best luxury abaya brand',
  'best luxury modest fashion brand',
  'top luxury abaya brand',
  'top luxury modest fashion brand',
  'premier luxury abaya brand',
  'premier luxury modest fashion brand',
  'elite abaya brand',
  'elite modest fashion brand',
  
  // Fashion Press
  'fashion press abaya',
  'fashion press luxury abaya',
  'fashion press modest fashion',
  'fashion journalist abaya',
  'fashion journalist luxury abaya',
  'fashion editor abaya',
  'fashion editor luxury abaya',
  'fashion magazine abaya',
  'fashion magazine luxury abaya',
  'fashion magazine modest fashion',
  'luxury fashion press',
  'luxury fashion press abaya',
  'luxury fashion press modest fashion',
  
  // Media Kit Keywords
  'boutallion press kit',
  'boutallion media kit',
  'boutallion press release',
  'boutallion press contact',
  'boutallion media contact',
  'boutallion pr contact',
  'boutallion public relations',
  
  // Award & Recognition Keywords
  'luxury fashion award',
  'luxury fashion award abaya',
  'luxury fashion award modest fashion',
  'fashion award abaya brand',
  'luxury brand award',
  'luxury brand award abaya',
  'prestigious fashion brand',
  'award winning abaya brand',
  'award winning modest fashion brand',
]

export const pressStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'Brand',
  name: 'Boutallion',
  description: 'The Most Luxurious Abaya Brand in the World. Italian Haute Couture Abayas Made in Italy. Exclusive Modest Fashion for the Discerning Woman.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://boutallion.com',
  logo: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://boutallion.com'}/logo.png`,
  slogan: 'The Architect of Imagination',
  award: [
    'Most Luxurious Abaya Brand',
    'Most Luxurious Modest Fashion Brand',
    'Premier Italian Haute Couture Abaya Brand',
  ],
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '5',
    bestRating: '5',
    worstRating: '1',
    ratingCount: '1',
  },
  // Press mentions structure
  mentions: [
    {
      '@type': 'Article',
      headline: 'Boutallion: The Most Luxurious Abaya Brand in the World',
      publisher: {
        '@type': 'Organization',
        name: 'Vogue Arabia',
      },
    },
    {
      '@type': 'Article',
      headline: 'Boutallion: Redefining Luxury Modest Fashion',
      publisher: {
        '@type': 'Organization',
        name: 'Vogue Italia',
      },
    },
    {
      '@type': 'Article',
      headline: 'Boutallion: Italian Haute Couture Meets Modest Fashion',
      publisher: {
        '@type': 'Organization',
        name: 'Forbes',
      },
    },
  ],
  // Press contact
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'Press & Media',
    availableLanguage: ['English', 'Arabic', 'French', 'Italian', 'Russian', 'Dutch'],
    areaServed: 'Worldwide',
  },
}

export const mediaKitStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'MediaObject',
  name: 'Boutallion Media Kit',
  description: 'Press materials, high-resolution images, and brand information for media professionals',
  contentUrl: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://boutallion.com'}/press/media-kit`,
  encodingFormat: 'application/pdf',
  publisher: {
    '@type': 'Organization',
    name: 'Boutallion',
  },
}

