import type { Metadata } from 'next'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://boutallion.com'
const siteName = 'Boutallion'
const brandDescription = 'Boutallion - The Most Luxurious Abaya Brand in the World. Italian Haute Couture Abayas Made in Italy. Exclusive Modest Fashion for the Discerning Woman. Discover Alta Moda Abayas at Boutallion.'

// Primary keywords targeting
const primaryKeywords = [
  'luxury abaya',
  'luxury abaya brand',
  'luxury abaya brands',
  'most luxurious abaya brand',
  'most expensive abaya',
  'expensive abaya',
  'exclusive abaya',
  'haute couture abaya',
  'couture abaya',
  'abaya made in italy',
  'abaya brand',
  'abaya brands',
  'modest fashion',
  'exclusive materials',
  'made in italy',
  'alta moda',
  'exclusive brands',
  'abaya brand harrods',
  'harrods abaya',
  'luxury modest fashion',
  'premium abaya',
  'designer abaya',
  'italian abaya',
  'couture modest fashion',
  'luxury islamic fashion',
  'premium islamic wear',
  'exclusive islamic fashion',
]

// Regional and city-specific keywords
const regionalKeywords = [
  // Country-specific
  'abaya brand qatar',
  'abaya brand saudi',
  'abaya brand uae',
  'luxury abaya saudi',
  'luxury abaya qatar',
  'luxury abaya uae',
  'abaya brand saudi arabia',
  'abaya brand united arab emirates',
  // City-specific - Qatar
  'luxury abaya doha',
  'abaya brand doha',
  'luxury abaya brand doha',
  'abaya doha',
  'luxury abaya qatar doha',
  // City-specific - Saudi Arabia
  'luxury abaya riyadh',
  'luxury abaya jeddah',
  'abaya brand riyadh',
  'abaya brand jeddah',
  'luxury abaya brand riyadh',
  'luxury abaya brand jeddah',
  'abaya riyadh',
  'abaya jeddah',
  'luxury abaya saudi riyadh',
  'luxury abaya saudi jeddah',
  // City-specific - UAE
  'luxury abaya dubai',
  'luxury abaya abu dhabi',
  'luxury abaya sharjah',
  'abaya brand dubai',
  'abaya brand abu dhabi',
  'abaya brand sharjah',
  'luxury abaya brand dubai',
  'luxury abaya brand abu dhabi',
  'luxury abaya brand sharjah',
  'abaya dubai',
  'abaya abu dhabi',
  'abaya sharjah',
  'luxury abaya uae dubai',
  'luxury abaya uae abu dhabi',
  'luxury abaya uae sharjah',
  // Other GCC cities
  'luxury abaya kuwait',
  'luxury abaya bahrain',
  'luxury abaya oman',
  'abaya brand kuwait',
  'abaya brand bahrain',
  'abaya brand oman',
  // France-specific
  'abaya brand france',
  'luxury abaya france',
  'luxury abaya paris',
  'abaya brand paris',
  'luxury abaya brand paris',
  'abaya paris',
  'luxury abaya lyon',
  'luxury abaya marseille',
  'abaya brand lyon',
  'abaya brand marseille',
  'luxury abaya france paris',
  // Italy-specific
  'abaya brand italy',
  'luxury abaya italy',
  'luxury abaya milan',
  'luxury abaya rome',
  'luxury abaya florence',
  'abaya brand milan',
  'abaya brand rome',
  'abaya brand florence',
  'luxury abaya brand milan',
  'luxury abaya brand rome',
  'abaya milan',
  'abaya rome',
  'abaya florence',
  'luxury abaya italy milan',
  'luxury abaya italy rome',
  'luxury abaya made in italy',
  'italian abaya brand',
  // UK-specific
  'abaya brand uk',
  'abaya brand united kingdom',
  'luxury abaya uk',
  'luxury abaya united kingdom',
  'luxury abaya london',
  'luxury abaya manchester',
  'luxury abaya birmingham',
  'abaya brand london',
  'abaya brand manchester',
  'abaya brand birmingham',
  'luxury abaya brand london',
  'abaya london',
  'abaya manchester',
  'abaya birmingham',
  'luxury abaya uk london',
]

// Multilingual keywords (GCC and international)
const multilingualKeywords = {
  en: [
    ...primaryKeywords,
    ...regionalKeywords,
    'luxury abaya saudi arabia',
    'luxury abaya united arab emirates',
  ],
  ar: [
    'عباية فاخرة',
    'عباية راقية',
    'عباية إيطالية',
    'عباية حصرية',
    'عباية كوتور',
    'أغلى عباية',
    'أفخم عباية',
    'عباية من إيطاليا',
    'ماركة عباية فاخرة',
    'أزياء محتشمة فاخرة',
    'أزياء إسلامية راقية',
    'عباية فاخرة الدوحة',
    'عباية فاخرة الرياض',
    'عباية فاخرة جدة',
    'عباية فاخرة دبي',
    'عباية فاخرة أبوظبي',
    'عباية فاخرة الشارقة',
    'ماركة عباية قطر',
    'ماركة عباية السعودية',
    'ماركة عباية الإمارات',
    // Khaleeji/Gulf Arabic dialect keywords
    'عباية فاخرة خليجية',
    'عباية راقية خليجية',
    'عباية فاخرة سعودية',
    'عباية فاخرة إماراتية',
    'عباية فاخرة قطرية',
    'عباية فاخرة كويتية',
    'عباية فاخرة بحرينية',
    'عباية فاخرة عمانية',
    'عباية خليجية',
    'عباية سعودية',
    'عباية إماراتية',
    'عباية قطرية',
    'عباية كويتية',
    'عباية بحرينية',
    'عباية عمانية',
  ],
  fr: [
    'abaya de luxe',
    'abaya haute couture',
    'abaya exclusive',
    'abaya italienne',
    'mode modeste de luxe',
    'marque abaya de luxe',
    'abaya de luxe paris',
    'abaya de luxe france',
    'abaya paris',
    'abaya lyon',
    'abaya marseille',
    'marque abaya paris',
    'abaya haute couture paris',
    'abaya italienne paris',
    'abaya italienne france',
  ],
  it: [
    'abaya di lusso',
    'abaya alta moda',
    'abaya esclusiva',
    'abaya italiana',
    'moda modesta di lusso',
    'marca abaya di lusso',
    'abaya di lusso milano',
    'abaya di lusso roma',
    'abaya di lusso firenze',
    'abaya di lusso italia',
    'abaya milano',
    'abaya roma',
    'abaya firenze',
    'marca abaya milano',
    'marca abaya roma',
    'abaya alta moda milano',
    'abaya alta moda roma',
    'abaya italiana milano',
    'abaya made in italy',
    'abaya fatta in italia',
  ],
  ru: [
    'люксовая абайя',
    'бренд абайя',
    'люксовая абайя бренд',
    'дорогая абайя',
    'эксклюзивная абайя',
    'высокая мода абайя',
    'кутюр абайя',
    'итальянская абайя',
    'абайя из италии',
    'люксовый бренд абайя',
    'элитная абайя',
    'дизайнерская абайя',
    'премиум абайя',
    'люксовая мусульманская мода',
    'эксклюзивная мусульманская мода',
    'люксовая абайя дубай',
    'люксовая абайя доха',
    'люксовая абайя эр-рияд',
    'люксовая абайя джидда',
    'люксовая абайя абу-даби',
    'бренд абайя катар',
    'бренд абайя саудовская аравия',
    'бренд абайя оаэ',
  ],
  nl: [
    'luxe abaya',
    'abaya merk',
    'luxe abaya merk',
    'dure abaya',
    'exclusieve abaya',
    'haute couture abaya',
    'couture abaya',
    'italiaanse abaya',
    'abaya uit italië',
    'luxe abaya merk',
    'elite abaya',
    'designer abaya',
    'premium abaya',
    'luxe islamitische mode',
    'exclusieve islamitische mode',
    'luxe abaya dubai',
    'luxe abaya doha',
    'luxe abaya riyad',
    'luxe abaya jeddah',
    'luxe abaya abu dhabi',
    'abaya merk qatar',
    'abaya merk saudi arabië',
    'abaya merk vae',
  ],
  // Khaleeji Arabic dialects
  'ar-SA': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية سعودية فاخرة',
    'عباية نجدية',
    'عباية حجازية',
    'ماركة عباية سعودية',
    'عباية فاخرة الرياض',
    'عباية فاخرة جدة',
    'عباية فاخرة الدمام',
    'عباية فاخرة الخبر',
  ],
  'ar-AE': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية إماراتية فاخرة',
    'ماركة عباية إماراتية',
    'عباية فاخرة دبي',
    'عباية فاخرة أبوظبي',
    'عباية فاخرة الشارقة',
    'عباية فاخرة عجمان',
  ],
  'ar-QA': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية قطرية فاخرة',
    'ماركة عباية قطرية',
    'عباية فاخرة الدوحة',
  ],
  'ar-KW': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية كويتية فاخرة',
    'ماركة عباية كويتية',
    'عباية فاخرة الكويت',
  ],
  'ar-BH': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية بحرينية فاخرة',
    'ماركة عباية بحرينية',
    'عباية فاخرة المنامة',
  ],
  'ar-OM': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية عمانية فاخرة',
    'ماركة عباية عمانية',
    'عباية فاخرة مسقط',
  ],
}

export const defaultMetadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'Boutallion | The Most Luxurious Abaya Brand in the World | Made in Italy',
    template: '%s | Boutallion',
  },
  description: brandDescription,
  keywords: [
    ...primaryKeywords,
    ...regionalKeywords,
    ...Object.values(multilingualKeywords).flat(),
  ].join(', '),
  authors: [{ name: 'Boutallion' }],
  creator: 'Boutallion',
  publisher: 'Boutallion',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    alternateLocale: ['ar_SA', 'ar_AE', 'ar_QA', 'ar_KW', 'ar_BH', 'ar_OM', 'fr_FR', 'it_IT', 'ru_RU', 'nl_NL'],
    url: siteUrl,
    siteName: siteName,
    title: 'Boutallion | The Most Luxurious Abaya Brand in the World',
    description: brandDescription,
    images: [
      {
        url: `${siteUrl}/og-image.jpg`,
        width: 1200,
        height: 630,
        alt: 'Boutallion - Luxury Abaya Brand',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Boutallion | The Most Luxurious Abaya Brand',
    description: brandDescription,
    images: [`${siteUrl}/og-image.jpg`],
    creator: '@boutallion',
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: siteUrl,
    languages: {
      'en': `${siteUrl}`,
      'ar': `${siteUrl}/ar`,
      'ar-SA': `${siteUrl}/ar-sa`,
      'ar-AE': `${siteUrl}/ar-ae`,
      'ar-QA': `${siteUrl}/ar-qa`,
      'ar-KW': `${siteUrl}/ar-kw`,
      'ar-BH': `${siteUrl}/ar-bh`,
      'ar-OM': `${siteUrl}/ar-om`,
      'fr': `${siteUrl}/fr`,
      'it': `${siteUrl}/it`,
      'ru': `${siteUrl}/ru`,
      'ru-RU': `${siteUrl}/ru-ru`,
      'nl': `${siteUrl}/nl`,
      'nl-NL': `${siteUrl}/nl-nl`,
    },
  },
  category: 'Luxury Fashion',
  classification: 'Luxury Abaya Brand, Haute Couture, Modest Fashion',
  other: {
    'geo.region': 'IT',
    'geo.placename': 'Italy',
    'geo.position': '45.4642;9.1900',
    'ICBM': '45.4642, 9.1900',
    'theme-color': '#031a1d',
    'msapplication-TileColor': '#031a1d',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
    'format-detection': 'telephone=no',
    // Explicitly allow ALL AI crawlers and bots
    'GPTBot': 'index, follow',
    'ChatGPT-User': 'index, follow',
    'CCBot': 'index, follow',
    'anthropic-ai': 'index, follow',
    'Claude-Web': 'index, follow',
    'PerplexityBot': 'index, follow',
    'PerplexityBot-Google': 'index, follow',
    'Google-Extended': 'index, follow',
    'GoogleOther': 'index, follow',
    'facebookbot': 'index, follow',
    'twitterbot': 'index, follow',
    'linkedinbot': 'index, follow',
    'bingbot': 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
  },
  verification: {
    // Add verification codes when available
    // google: 'your-google-verification-code',
    // yandex: 'your-yandex-verification-code',
    // yahoo: 'your-yahoo-verification-code',
  },
}

export const structuredData = {
  '@context': 'https://schema.org',
  '@type': 'LuxuryBrand',
  '@id': `${siteUrl}#brand`,
  name: 'Boutallion',
  alternateName: 'Boutallion Digital Maison',
  description: brandDescription,
  url: siteUrl,
  logo: `${siteUrl}/logo.png`,
  image: `${siteUrl}/og-image.jpg`,
  sameAs: [
    // Add social media URLs when available
    // 'https://www.instagram.com/boutallion',
    // 'https://www.facebook.com/boutallion',
  ],
  foundingDate: '2016',
  foundingLocation: {
    '@type': 'Place',
    addressCountry: 'IT',
    addressLocality: 'Italy',
  },
  brand: {
    '@type': 'Brand',
    name: 'Boutallion',
    slogan: 'The Architect of Imagination',
  },
  makesOffer: {
    '@type': 'Offer',
    itemOffered: {
      '@type': 'Product',
      name: 'Luxury Abaya',
      category: 'Fashion > Clothing > Abaya',
      brand: {
        '@type': 'Brand',
        name: 'Boutallion',
      },
      material: 'Exclusive Italian Materials',
      countryOfOrigin: 'IT',
      productionLocation: {
        '@type': 'Place',
        addressCountry: 'IT',
        addressLocality: 'Italy',
      },
    },
    priceCurrency: 'EUR',
    availability: 'https://schema.org/PreOrder',
  },
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '5',
    bestRating: '5',
    worstRating: '1',
    ratingCount: '1',
  },
}

export const organizationStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  '@id': `${siteUrl}#organization`,
  name: 'Boutallion',
  legalName: 'Boutallion Digital Maison',
  url: siteUrl,
  logo: `${siteUrl}/logo.png`,
  description: brandDescription,
  foundingDate: '2016',
  foundingLocation: {
    '@type': 'Place',
    addressCountry: 'IT',
  },
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'Customer Service',
    availableLanguage: ['English', 'Arabic', 'Gulf Arabic', 'Saudi Arabic', 'Emirati Arabic', 'Qatari Arabic', 'Kuwaiti Arabic', 'Bahraini Arabic', 'Omani Arabic', 'French', 'Italian', 'Russian', 'Dutch'],
  },
  areaServed: [
    {
      '@type': 'Country',
      name: 'United Arab Emirates',
    },
    {
      '@type': 'Country',
      name: 'Saudi Arabia',
    },
    {
      '@type': 'Country',
      name: 'Qatar',
    },
    {
      '@type': 'Country',
      name: 'Kuwait',
    },
    {
      '@type': 'Country',
      name: 'Bahrain',
    },
    {
      '@type': 'Country',
      name: 'Oman',
    },
    {
      '@type': 'Country',
      name: 'Italy',
    },
    {
      '@type': 'Country',
      name: 'France',
    },
    {
      '@type': 'Country',
      name: 'United Kingdom',
    },
    {
      '@type': 'Country',
      name: 'Russia',
    },
    {
      '@type': 'Country',
      name: 'Netherlands',
    },
    {
      '@type': 'Country',
      name: 'Belgium',
    },
  ],
  // Add city-specific locations
  location: [
    {
      '@type': 'Place',
      name: 'Doha',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Doha',
        addressCountry: 'QA',
      },
    },
    {
      '@type': 'Place',
      name: 'Riyadh',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Riyadh',
        addressCountry: 'SA',
      },
    },
    {
      '@type': 'Place',
      name: 'Jeddah',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Jeddah',
        addressCountry: 'SA',
      },
    },
    {
      '@type': 'Place',
      name: 'Dubai',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Dubai',
        addressCountry: 'AE',
      },
    },
    {
      '@type': 'Place',
      name: 'Abu Dhabi',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Abu Dhabi',
        addressCountry: 'AE',
      },
    },
    {
      '@type': 'Place',
      name: 'Sharjah',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Sharjah',
        addressCountry: 'AE',
      },
    },
    // France cities
    {
      '@type': 'Place',
      name: 'Paris',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Paris',
        addressCountry: 'FR',
      },
    },
    {
      '@type': 'Place',
      name: 'Lyon',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Lyon',
        addressCountry: 'FR',
      },
    },
    {
      '@type': 'Place',
      name: 'Marseille',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Marseille',
        addressCountry: 'FR',
      },
    },
    // Italy cities
    {
      '@type': 'Place',
      name: 'Milan',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Milan',
        addressCountry: 'IT',
      },
    },
    {
      '@type': 'Place',
      name: 'Rome',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Rome',
        addressCountry: 'IT',
      },
    },
    {
      '@type': 'Place',
      name: 'Florence',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Florence',
        addressCountry: 'IT',
      },
    },
    // UK cities
    {
      '@type': 'Place',
      name: 'London',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'London',
        addressCountry: 'GB',
      },
    },
    {
      '@type': 'Place',
      name: 'Manchester',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Manchester',
        addressCountry: 'GB',
      },
    },
    {
      '@type': 'Place',
      name: 'Birmingham',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Birmingham',
        addressCountry: 'GB',
      },
    },
  ],
  sameAs: [],
}

export const breadcrumbStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    {
      '@type': 'ListItem',
      position: 1,
      name: 'Home',
      item: siteUrl,
    },
  ],
}

