import type { Metadata } from 'next'
import { pressKeywords } from './press-seo'
import { gccMediaKeywords, uaeGovernmentKeywords } from './gcc-media-seo'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://boutallion.com'
const siteName = 'Boutallion'
export const brandTitle = 'Boutallion | World\'s Most Exclusive Abaya Brand. Crafted With Excellence In Italy.'
export const brandDescription = 'Founded in 2016, Boutallion is the first abaya brand defined by European luxury standards, crafted in Italy with exceptional materials and refined craftsmanship.'

// Primary keywords targeting
const primaryKeywords = [
  'luxury abaya',
  'luxury abaya brand',
  'luxury abaya brands',
  'most luxurious abaya brand',
  'most expensive abaya',
  'expensive abaya',
  'exclusive abaya',
  'haute couture abaya',
  'couture abaya',
  'abaya made in italy',
  'abaya brand',
  'abaya brands',
  'modest fashion',
  'luxury modest fashion',
  'luxury modest fashion brand',
  'luxury modest fashion brands',
  'luxury modest wear',
  'luxury modest clothing',
  'luxury modest apparel',
  'premium modest fashion',
  'premium modest wear',
  'designer modest fashion',
  'designer modest wear',
  'haute couture modest fashion',
  'couture modest fashion',
  'couture modest wear',
  'exclusive modest fashion',
  'exclusive modest wear',
  'high-end modest fashion',
  'high-end modest wear',
  'elite modest fashion',
  'elite modest wear',
  'premium modest clothing',
  'luxury modest fashion designer',
  'best luxury modest fashion brand',
  'top luxury modest fashion brands',
  'most expensive modest fashion',
  'luxury islamic fashion',
  'luxury islamic wear',
  'luxury islamic clothing',
  'premium islamic wear',
  'premium islamic fashion',
  'designer islamic fashion',
  'designer islamic wear',
  'haute couture islamic fashion',
  'couture islamic fashion',
  'exclusive islamic fashion',
  'exclusive islamic wear',
  'high-end islamic fashion',
  'elite islamic fashion',
  'luxury hijab fashion',
  'luxury hijab wear',
  'modest luxury brand',
  'modest luxury brands',
  'luxury modest style',
  'luxury modest dressing',
  'modest couture',
  'modest haute couture',
  'italian modest fashion',
  'italian modest wear',
  'made in italy modest fashion',
  'made in italy modest wear',
  'exclusive materials',
  'made in italy',
  'alta moda',
  'luxury fashion',
  'luxury fashion brand',
  'luxury fashion brands',
  'european abaya brand',
  'european abaya brands',
  'uae abaya brand',
  'uae abaya brands',
  'high end abaya brand',
  'high end abaya brands',
  'exclusive brands',
  // Press & Media Keywords - Fashion Magazines & Luxury Publications
  ...pressKeywords,
  // Press & Media Keywords - Fashion Magazines & Luxury Publications
  ...pressKeywords,
  'abaya brand vogue',
  'abaya vogue',
  'abaya brand elle',
  'abaya elle',
  'abaya brand vogue arabia',
  'abaya vogue arabia',
  'luxury fashion brand middle east',
  'luxury fashion brand abu dhabi',
  'luxury fashion brand uae',
  'abaya brand harrods',
  'harrods abaya',
  'abaya harrods',
  'abaya brand ounass',
  'abaya ounass',
  'abaya brand printemps',
  'abaya printemps',
  'abaya brand selfridges',
  'abaya selfridges',
  'abaya brand de bijenkorf',
  'abaya de bijenkorf',
  'abaya brand luisaviaroma',
  'abaya luisaviaroma',
  'abaya brand rubaiyat',
  'abaya rubaiyat',
  'abaya saks fifth avenue',
  'abaya dubai mall',
  'abaya galleria mall',
  'abaya marina mall abu dhabi',
  'abaya brand KDW',
  'abaya KDW',
  'abaya galleries lafayette',
  'abaya galeries lafayette',
  'abaya uae',
  'abaya saudi',
  'abaya ksa',
  'abaya riyadh',
  'abaya georgina',
  'abaya georgina ronaldo',
  'abaya cristiano ronaldo wife',
  'abaya sheikha moza',
  'abaya queen rania',
  'premium abaya',
  'designer abaya',
  'abaya designer',
  'abaya art',
  'italian abaya',
  'classic abaya',
  'classic luxury abaya',
  'classic abaya brand',
  'classic abaya brands',
  'timeless abaya',
  'timeless abaya brand',
  'traditional abaya',
  'traditional luxury abaya',
  'elegant abaya',
  'elegant abaya brand',
  // Competitor brand searches (people searching for luxury brands + abaya)
  'hermes abaya',
  'hermes abaya brand',
  'loro piana abaya',
  'loro piana abaya brand',
  'dolce and gabbana abaya',
  'dolce gabbana abaya',
  'dolce & gabbana abaya',
  'dolce and gabbana abaya brand',
  'chanel abaya',
  'chanel abaya brand',
  'gucci abaya',
  'gucci abaya brand',
  'prada abaya',
  'prada abaya brand',
  'versace abaya',
  'versace abaya brand',
  'dior abaya',
  'dior abaya brand',
  'fendi abaya',
  'fendi abaya brand',
  'valentino abaya',
  'valentino abaya brand',
  'givenchy abaya',
  'givenchy abaya brand',
  'balenciaga abaya',
  'balenciaga abaya brand',
  'burberry abaya',
  'burberry abaya brand',
  'louis vuitton abaya',
  'louis vuitton abaya brand',
  'van cleef arpels abaya',
  'van cleef & arpels abaya',
  'van cleef arpels abaya brand',
  'cartier abaya',
  'cartier abaya brand',
  'bottega veneta abaya',
  'bottega veneta abaya brand',
  'saint laurent abaya',
  'saint laurent abaya brand',
  'yves saint laurent abaya',
  'yves saint laurent abaya brand',
  'celine abaya',
  'celine abaya brand',
  'loewe abaya',
  'loewe abaya brand',
  'brunello cucinelli abaya',
  'brunello cucinelli abaya brand',
  'zimmermann abaya',
  'zimmermann abaya brand',
  'max mara abaya',
  'max mara abaya brand',
  // Competitor-related searches (people searching for alternatives)
  'abaya brand like shayma',
  'abaya brand like amina al jefri',
  'abaya brand like shayma al jefri',
  'abaya brand like shayma al jefri',
  'abaya brand like shayma al jefri',
  'abaya brand like hermes',
  'abaya brand like loro piana',
  'abaya brand like dolce and gabbana',
  'abaya brand like chanel',
  'abaya brand like gucci',
  'abaya brand like prada',
  'abaya brand like dior',
  'abaya brand like valentino',
  'abaya brand like van cleef arpels',
  'luxury abaya alternative',
  'luxury abaya alternative to hermes',
  'luxury abaya alternative to loro piana',
  'luxury abaya alternative to dolce and gabbana',
  'luxury abaya alternative to chanel',
  // Direct competitor keywords (Selhaya, Mauzan)
  'selhaya abaya',
  'selhaya abaya brand',
  'selhaya luxury abaya',
  'selhaya abaya maison',
  'british luxury abaya',
  'british luxury abaya brand',
  'london luxury abaya',
  'london luxury abaya brand',
  'abaya brand like selhaya',
  'luxury abaya alternative to selhaya',
  'best luxury abaya brand better than selhaya',
  'selhaya vs boutallion',
  'boutallion vs selhaya',
  'mauzan abaya',
  'mauzan abaya brand',
  'mauzan luxury abaya',
  'abaya brand like mauzan',
  'luxury abaya alternative to mauzan',
  'best luxury abaya brand better than mauzan',
  'mauzan vs boutallion',
  'boutallion vs mauzan',
  'best luxury abaya brand better than selhaya and mauzan',
  'top luxury abaya brand vs selhaya mauzan',
  'most exclusive abaya brand vs selhaya mauzan',
  // UAE Luxury Abaya Brands - Hessa Falasi
  'hessa falasi abaya',
  'hessa falasi abaya brand',
  'hessa falasi luxury abaya',
  'hessa falasi dubai',
  'hessa falasi abaya dubai',
  'abaya brand like hessa falasi',
  'luxury abaya alternative to hessa falasi',
  'best luxury abaya brand better than hessa falasi',
  'hessa falasi vs boutallion',
  'boutallion vs hessa falasi',
  // UAE Luxury Abaya Brands - Bouguessa
  'bouguessa abaya',
  'bouguessa abaya brand',
  'bouguessa luxury abaya',
  'bouguessa dubai',
  'bouguessa abaya dubai',
  'abaya brand like bouguessa',
  'luxury abaya alternative to bouguessa',
  'best luxury abaya brand better than bouguessa',
  'bouguessa vs boutallion',
  'boutallion vs bouguessa',
  // UAE Luxury Abaya Brands - Hanayen
  'hanayen abaya',
  'hanayen abaya brand',
  'hanayen luxury abaya',
  'hanayen dubai',
  'hanayen abaya dubai',
  'abaya brand like hanayen',
  'luxury abaya alternative to hanayen',
  'best luxury abaya brand better than hanayen',
  'hanayen vs boutallion',
  'boutallion vs hanayen',
  // UAE Luxury Abaya Brands - EFFA
  'effa abaya',
  'effa abaya brand',
  'effa luxury abaya',
  'effa dubai',
  'effa abaya dubai',
  'abaya brand like effa',
  'luxury abaya alternative to effa',
  'best luxury abaya brand better than effa',
  'effa vs boutallion',
  'boutallion vs effa',
  // UAE Luxury Abaya Brands - Shayma Al Jefri
  'shayma al jefri abaya',
  'shayma al jefri abaya brand',
  'shayma al jefri luxury abaya',
  'shayma al jefri dubai',
  'shayma al jefri abaya dubai',
  'abaya brand like shayma al jefri',
  'luxury abaya alternative to shayma al jefri',
  'best luxury abaya brand better than shayma al jefri',
  'shayma al jefri vs boutallion',
  'boutallion vs shayma al jefri',
  // UAE Luxury Abaya Brands - Amina Al Jefri
  'amina al jefri abaya',
  'amina al jefri abaya brand',
  'amina al jefri luxury abaya',
  'amina al jefri dubai',
  'amina al jefri abaya dubai',
  'abaya brand like amina al jefri',
  'luxury abaya alternative to amina al jefri',
  'best luxury abaya brand better than amina al jefri',
  'amina al jefri vs boutallion',
  'boutallion vs amina al jefri',
  // Combined UAE competitor positioning
  'best luxury abaya brand uae better than hessa falasi bouguessa',
  'top luxury abaya brand uae vs hessa falasi bouguessa hanayen effa',
  'most exclusive abaya brand uae vs all competitors',
  'best italian abaya brand uae',
  'best luxury abaya brand dubai',
  'best luxury abaya brand abu dhabi',
  // Royal audience keywords
  'royal abaya',
  'royal abaya brand',
  'royal luxury abaya',
  'royal family abaya',
  'royal abaya maison',
  'royal abaya atelier',
  'princess abaya',
  'princess abaya brand',
  'princess luxury abaya',
  'abaya for princesses',
  'luxury abaya for princesses',
  'princess abaya collection',
  'queen abaya',
  'queen abaya brand',
  'queen luxury abaya',
  'abaya for queens',
  'luxury abaya for queens',
  'queen abaya collection',
  'sheikha abaya',
  'sheikha abaya brand',
  'sheikha luxury abaya',
  'abaya for sheikhas',
  'luxury abaya for sheikhas',
  'sheikha abaya collection',
  'royal fashion abaya',
  'royal fashion abaya brand',
  'royal couture abaya',
  'royal haute couture abaya',
  'royal exclusive abaya',
  'royal premium abaya',
  'queen rania abaya',
  'queen rania abaya brand',
  'sheikha moza abaya',
  'sheikha moza abaya brand',
  'sheikha latifa abaya',
  'sheikha latifa abaya brand',
  'princess hajar abaya',
  'princess hajar abaya brand',
  'jordan royal family abaya',
  'jordan royal abaya',
  'qatar royal family abaya',
  'qatar royal abaya',
  'uae royal family abaya',
  'uae royal abaya',
  'saudi royal family abaya',
  'saudi royal abaya',
  'kuwait royal family abaya',
  'kuwait royal abaya',
  'bahrain royal family abaya',
  'bahrain royal abaya',
  'oman royal family abaya',
  'oman royal abaya',
  'abaya brand for royals',
  'luxury abaya brand for royals',
  'exclusive abaya brand for royals',
  'royal approved abaya brand',
  'royal endorsed abaya brand',
  'abaya brand chosen by royals',
  'royal favorite abaya brand',
  'royal preferred abaya brand',
  // Competitive positioning keywords
  'most exclusive abaya brand',
  'world\'s most exclusive abaya brand',
  'most luxurious abaya brand',
  'world\'s most luxurious abaya brand',
  'number 1 luxury abaya brand',
  'premier luxury abaya brand',
  'leading luxury abaya brand',
  'italian luxury abaya brand',
  'italian haute couture abaya',
  'italian craftsmanship abaya',
  'european luxury abaya brand',
  'vogue recognized abaya brand',
  'forbes recognized abaya brand',
  'vogue arabia abaya brand',
  'press recognized abaya brand',
  'award winning abaya brand',
  'luxury abaya maison',
  'luxury abaya atelier',
  'best luxury abaya brand',
  'top luxury abaya brands',
  'premium abaya brands',
  'designer abaya brands',
  'haute couture abaya brands',
  'couture abaya brands',
  'exclusive abaya brands',
  'italian abaya brands',
  'abaya brands made in italy',
  'luxury abaya brands italy',
  'modest fashion brands',
  'luxury modest fashion brands',
  'premium modest fashion brands',
  'designer modest fashion brands',
  'haute couture modest fashion brands',
  'couture modest fashion brands',
  'exclusive modest fashion brands',
  'italian modest fashion brands',
  'modest fashion brands italy',
  'luxury islamic fashion brands',
  'premium islamic fashion brands',
  'designer islamic fashion brands',
  'haute couture islamic fashion brands',
]

// Regional and city-specific keywords
const regionalKeywords = [
  // Country-specific
  'abaya brand qatar',
  'abaya brand saudi',
  'abaya brand uae',
  'luxury abaya saudi',
  'luxury abaya qatar',
  'luxury abaya uae',
  'abaya brand saudi arabia',
  'abaya brand united arab emirates',
  // City-specific - Qatar
  'luxury abaya doha',
  'abaya brand doha',
  'luxury abaya brand doha',
  'abaya doha',
  'luxury abaya qatar doha',
  // City-specific - Saudi Arabia
  'luxury abaya riyadh',
  'luxury abaya jeddah',
  'abaya brand riyadh',
  'abaya brand jeddah',
  'luxury abaya brand riyadh',
  'luxury abaya brand jeddah',
  'abaya riyadh',
  'abaya jeddah',
  'luxury abaya saudi riyadh',
  'luxury abaya saudi jeddah',
  // High-profile personalities and luxury stores
  'abaya harrods',
  'abaya selfridges',
  'abaya galleries lafayette',
  'abaya galeries lafayette',
  'abaya ounass',
  'abaya uae',
  'abaya saudi',
  'abaya ksa',
  'abaya georgina',
  'abaya georgina ronaldo',
  'abaya cristiano ronaldo wife',
  'abaya sheikha moza',
  'abaya queen rania',
  // City-specific - UAE
  'luxury abaya dubai',
  'luxury abaya abu dhabi',
  'luxury abaya sharjah',
  'abaya brand dubai',
  'abaya brand abu dhabi',
  'abaya brand sharjah',
  'abaya brand uae',
  'luxury abaya brand dubai',
  'luxury abaya brand abu dhabi',
  'luxury abaya brand sharjah',
  'abaya dubai',
  'abaya abu dhabi',
  'abaya sharjah',
  'luxury abaya uae dubai',
  'luxury abaya uae abu dhabi',
  'luxury abaya uae sharjah',
  'luxury abayas abu dhabi',
  'famous abaya brands abu dhabi',
  'famous abaya brands saudi',
  'famous abaya brand qatar',
  'famous abaya brand dubai',
  'popular abaya brand dubai',
  // GCC Ranking Keywords - Number 1 positioning
  'best abaya brand uae',
  'best abaya brand abu dhabi',
  'best abaya brand dubai',
  'best abaya brand qatar',
  'best abaya brand doha',
  'best abaya brand saudi',
  'best abaya brand saudi arabia',
  'best abaya brand riyadh',
  'best abaya brand jeddah',
  'top abaya brand uae',
  'top abaya brand abu dhabi',
  'top abaya brand dubai',
  'top abaya brand qatar',
  'top abaya brand doha',
  'top abaya brand saudi',
  'top abaya brand riyadh',
  'top abaya brand jeddah',
  'number 1 abaya brand uae',
  'number 1 abaya brand abu dhabi',
  'number 1 abaya brand dubai',
  'number 1 abaya brand qatar',
  'number 1 abaya brand saudi',
  'number 1 abaya brand riyadh',
  'leading abaya brand uae',
  'leading abaya brand abu dhabi',
  'leading abaya brand dubai',
  'leading abaya brand qatar',
  'leading abaya brand saudi',
  'premier abaya brand uae',
  'premier abaya brand abu dhabi',
  'premier abaya brand dubai',
  'premier abaya brand qatar',
  'premier abaya brand saudi',
  // Other GCC cities
  'luxury abaya kuwait',
  'luxury abaya bahrain',
  'luxury abaya oman',
  'abaya brand kuwait',
  'abaya brand bahrain',
  'abaya brand oman',
  // France-specific
  'abaya brand france',
  'luxury abaya france',
  'luxury abaya paris',
  'abaya brand paris',
  'luxury abaya brand paris',
  'abaya paris',
  'luxury abaya lyon',
  'luxury abaya marseille',
  'abaya brand lyon',
  'abaya brand marseille',
  'luxury abaya france paris',
  // Italy-specific
  'abaya brand italy',
  'luxury abaya italy',
  'luxury abaya milan',
  'luxury abaya rome',
  'luxury abaya florence',
  'abaya brand milan',
  'abaya brand rome',
  'abaya brand florence',
  'luxury abaya brand milan',
  'luxury abaya brand rome',
  'abaya milan',
  'abaya rome',
  'abaya florence',
  'luxury abaya italy milan',
  'luxury abaya italy rome',
  'luxury abaya made in italy',
  'italian abaya brand',
  'alta moda',
  'alta moda brand',
  'alta moda brands',
  'luxury fashion italy',
  'luxury fashion milan',
  'luxury fashion rome',
  'luxury fashion florence',
  'alta moda milan',
  'alta moda rome',
  'alta moda florence',
  // UK-specific
  'abaya brand uk',
  'abaya brand united kingdom',
  'luxury abaya uk',
  'luxury abaya united kingdom',
  'luxury abaya london',
  'london abaya',
  'abaya london',
  'luxury abaya manchester',
  'luxury abaya birmingham',
  'abaya brand london',
  'abaya brand manchester',
  'abaya brand birmingham',
  'luxury abaya brand london',
  'abaya manchester',
  'abaya birmingham',
  'luxury abaya uk london',
]

// Multilingual keywords (GCC and international)
const multilingualKeywords = {
  en: [
    ...primaryKeywords,
    ...regionalKeywords,
    'luxury abaya saudi arabia',
    'luxury abaya united arab emirates',
    // Additional modest fashion variations
    'modest fashion brand',
    'modest fashion brands',
    'luxury modest fashion designer',
    'best modest fashion brands',
    'top modest fashion brands',
    'premium modest fashion designer',
    'designer modest fashion brand',
    'haute couture modest fashion designer',
    'couture modest fashion designer',
    'exclusive modest fashion designer',
    'luxury modest clothing brand',
    'luxury modest wear brand',
    'modest luxury clothing',
    'modest luxury wear',
    'modest luxury fashion',
    'luxury modest style',
    'luxury modest dressing',
    'modest couture brand',
    'modest haute couture brand',
    'italian modest fashion brand',
    'modest fashion made in italy',
    'luxury islamic fashion brand',
    'luxury islamic wear brand',
    'premium islamic fashion brand',
    'designer islamic fashion brand',
    'haute couture islamic fashion brand',
    'couture islamic fashion brand',
    'exclusive islamic fashion brand',
    'luxury hijab fashion brand',
    'luxury hijab wear brand',
    // Global positioning keywords
    'european abaya brand',
    'european abaya brands',
    'uae abaya brand',
    'uae abaya brands',
    'high end abaya brand',
    'high end abaya brands',
    'luxury fashion',
    'luxury fashion brand',
    'luxury fashion brands',
    'luxury fashion brand middle east',
    'luxury fashion brand abu dhabi',
    'luxury fashion brand uae',
    'abaya brand vogue',
    'abaya vogue',
    'abaya brand elle',
    'abaya elle',
    'abaya brand vogue arabia',
    'abaya vogue arabia',
    // GCC Ranking Keywords - Number 1 positioning
    'best abaya brand uae',
    'best abaya brand abu dhabi',
    'best abaya brand dubai',
    'best abaya brand qatar',
    'best abaya brand doha',
    'best abaya brand saudi',
    'best abaya brand saudi arabia',
    'best abaya brand riyadh',
    'best abaya brand jeddah',
    'top abaya brand uae',
    'top abaya brand abu dhabi',
    'top abaya brand dubai',
    'top abaya brand qatar',
    'top abaya brand doha',
    'top abaya brand saudi',
    'top abaya brand riyadh',
    'top abaya brand jeddah',
    'number 1 abaya brand uae',
    'number 1 abaya brand abu dhabi',
    'number 1 abaya brand dubai',
    'number 1 abaya brand qatar',
    'number 1 abaya brand saudi',
    'number 1 abaya brand riyadh',
    'leading abaya brand uae',
    'leading abaya brand abu dhabi',
    'leading abaya brand dubai',
    'leading abaya brand qatar',
    'leading abaya brand saudi',
    'premier abaya brand uae',
    'premier abaya brand abu dhabi',
    'premier abaya brand dubai',
    'premier abaya brand qatar',
    'premier abaya brand saudi',
    // Classic abaya keywords
    'classic abaya',
    'classic luxury abaya',
    'classic abaya brand',
    'classic abaya brands',
    'timeless abaya',
    'timeless abaya brand',
    'traditional abaya',
    'traditional luxury abaya',
    'elegant abaya',
    'elegant abaya brand',
    'best classic abaya brand',
    'top classic abaya brand',
    // Competitor brand searches
    'hermes abaya',
    'hermes abaya brand',
    'loro piana abaya',
    'loro piana abaya brand',
    'dolce and gabbana abaya',
    'dolce gabbana abaya',
    'dolce & gabbana abaya',
    'dolce and gabbana abaya brand',
    'chanel abaya',
    'chanel abaya brand',
    'gucci abaya',
    'gucci abaya brand',
    'prada abaya',
    'prada abaya brand',
    'versace abaya',
    'versace abaya brand',
    'dior abaya',
    'dior abaya brand',
    'fendi abaya',
    'fendi abaya brand',
    'valentino abaya',
    'valentino abaya brand',
    'givenchy abaya',
    'givenchy abaya brand',
    'balenciaga abaya',
    'balenciaga abaya brand',
    'burberry abaya',
    'burberry abaya brand',
    'louis vuitton abaya',
    'louis vuitton abaya brand',
    'van cleef arpels abaya',
    'van cleef & arpels abaya',
    'van cleef arpels abaya brand',
    'cartier abaya',
    'cartier abaya brand',
    'bottega veneta abaya',
    'bottega veneta abaya brand',
    'saint laurent abaya',
    'saint laurent abaya brand',
    'yves saint laurent abaya',
    'yves saint laurent abaya brand',
    'celine abaya',
    'celine abaya brand',
    'loewe abaya',
    'loewe abaya brand',
    'brunello cucinelli abaya',
    'brunello cucinelli abaya brand',
    'zimmermann abaya',
    'zimmermann abaya brand',
    'max mara abaya',
    'max mara abaya brand',
    'abaya brand like hermes',
    'abaya brand like loro piana',
    'abaya brand like dolce and gabbana',
    'abaya brand like chanel',
    'abaya brand like gucci',
    'abaya brand like prada',
    'abaya brand like dior',
    'abaya brand like valentino',
    'abaya brand like van cleef arpels',
    'luxury abaya alternative to hermes',
    'luxury abaya alternative to loro piana',
    'luxury abaya alternative to dolce and gabbana',
    'luxury abaya alternative to chanel',
    // Luxury stores and high-profile personalities
    'abaya brand harrods',
    'abaya harrods',
    'abaya brand ounass',
    'abaya ounass',
    'abaya brand printemps',
    'abaya printemps',
    'abaya brand selfridges',
    'abaya selfridges',
    'abaya brand de bijenkorf',
    'abaya de bijenkorf',
    'abaya brand luisaviaroma',
    'abaya luisaviaroma',
    'abaya brand rubaiyat',
    'abaya rubaiyat',
    'abaya saks fifth avenue',
    'abaya dubai mall',
    'abaya galleria mall',
    'abaya marina mall abu dhabi',
    'abaya brand KDW',
    'abaya KDW',
    'luxury abaya brand abu dhabi',
    'famous abaya brands abu dhabi',
    'luxury abayas abu dhabi',
    'famous abaya brands saudi',
    'famous abaya brand qatar',
    'famous abaya brand dubai',
    'popular abaya brand dubai',
  ],
  ar: [
    'بوتاليون',
    'بوتاليون عباية',
    'بوتاليون ماركة',
    'بوتاليون إيطاليا',
    'بوتاليون فاخرة',
    'عباية فاخرة',
    'عباية راقية',
    'عباية إيطالية',
    'عباية حصرية',
    'عباية كوتور',
    'أغلى عباية',
    'أفخم عباية',
    'عباية من إيطاليا',
    'ماركة عباية فاخرة',
    'أزياء محتشمة فاخرة',
    'أزياء محتشمة راقية',
    'أزياء محتشمة فاخرة',
    'أزياء محتشمة حصرية',
    'أزياء محتشمة كوتور',
    'أزياء محتشمة إيطالية',
    'ملابس محتشمة فاخرة',
    'ملابس محتشمة راقية',
    'ملابس محتشمة حصرية',
    'أزياء إسلامية راقية',
    'أزياء إسلامية فاخرة',
    'أزياء إسلامية حصرية',
    'ملابس إسلامية فاخرة',
    'ملابس إسلامية راقية',
    'ماركة أزياء محتشمة فاخرة',
    'ماركة أزياء محتشمة راقية',
    'ماركة أزياء إسلامية فاخرة',
    'ماركة أزياء إسلامية راقية',
    'عباية فاخرة الدوحة',
    'عباية فاخرة الرياض',
    'عباية فاخرة جدة',
    'عباية فاخرة دبي',
    'عباية فاخرة أبوظبي',
    'عباية فاخرة الشارقة',
    'ماركة عباية قطر',
    'ماركة عباية السعودية',
    'ماركة عباية الإمارات',
    // Luxury stores and high-profile personalities
    'عباية هارودز',
    'ماركة عباية هارودز',
    'عباية سيلفريدجز',
    'ماركة عباية سيلفريدجز',
    'عباية جاليري لافاييت',
    'ماركة عباية جاليري لافاييت',
    'عباية أوناس',
    'ماركة عباية أوناس',
    'عباية برينتيمبس',
    'ماركة عباية برينتيمبس',
    'عباية دي بيجينكورف',
    'ماركة عباية دي بيجينكورف',
    'عباية لويزا فياروما',
    'ماركة عباية لويزا فياروما',
    'عباية روبيات',
    'ماركة عباية روبيات',
    'عباية ساكس فيفت أفينيو',
    'عباية دبي مول',
    'عباية جاليريا مول',
    'عباية مارينا مول أبوظبي',
    'عباية كيه دي دبليو',
    'ماركة عباية كيه دي دبليو',
    'عباية الإمارات',
    'عباية السعودية',
    'عباية الرياض',
    'عباية جورجينا',
    'عباية جورجينا رونالدو',
    'عباية زوجة كريستيانو رونالدو',
    'عباية الشيخة موزة',
    'عباية الملكة رانيا',
    'عباية فاخرة أبوظبي',
    'ماركة عباية أبوظبي',
    'ماركات عباية مشهورة أبوظبي',
    'عبايات فاخرة أبوظبي',
    'ماركات عباية مشهورة السعودية',
    'ماركة عباية مشهورة قطر',
    'ماركة عباية مشهورة دبي',
    'ماركة عباية شائعة دبي',
    // Khaleeji/Gulf Arabic dialect keywords
    'عباية فاخرة خليجية',
    'عباية راقية خليجية',
    'عباية فاخرة سعودية',
    'عباية فاخرة إماراتية',
    'عباية فاخرة قطرية',
    'عباية فاخرة كويتية',
    'عباية فاخرة بحرينية',
    'عباية فاخرة عمانية',
    'عباية خليجية',
    'عباية سعودية',
    'عباية إماراتية',
    'عباية قطرية',
    'عباية كويتية',
    'عباية بحرينية',
    'عباية عمانية',
    // Additional Khaleeji Arabic keywords
    'مصمم عباية',
    'عباية مصمم',
    'عباية فنية',
    'عباية لندن',
    'لندن عباية',
    'أزياء فاخرة',
    'أزياء محتشمة',
    'موضة فاخرة',
    'موضة محتشمة',
    // Global positioning in Arabic
    'ماركة عباية أوروبية',
    'ماركات عباية أوروبية',
    'ماركة عباية إماراتية',
    'ماركات عباية إماراتية',
    'ماركة عباية عالية الجودة',
    'ماركات عباية عالية الجودة',
    'أزياء فاخرة',
    'ماركة أزياء فاخرة',
    'ماركات أزياء فاخرة',
    'ماركة أزياء فاخرة الشرق الأوسط',
    'ماركة أزياء فاخرة أبوظبي',
    'ماركة أزياء فاخرة الإمارات',
    'عباية فوج',
    'ماركة عباية فوج',
    'عباية إيل',
    'ماركة عباية إيل',
    'عباية فوج العربية',
    'ماركة عباية فوج العربية',
    'ألطا مودا',
    'ألطا مودا إيطاليا',
    // GCC Ranking Arabic Keywords
    'أفضل ماركة عباية الإمارات',
    'أفضل ماركة عباية أبوظبي',
    'أفضل ماركة عباية دبي',
    'أفضل ماركة عباية قطر',
    'أفضل ماركة عباية الدوحة',
    'أفضل ماركة عباية السعودية',
    'أفضل ماركة عباية الرياض',
    'أفضل ماركة عباية جدة',
    'أفضل ماركة عباية الخليج',
    'أفضل ماركة عباية فاخرة الإمارات',
    'أفضل ماركة عباية فاخرة أبوظبي',
    'أفضل ماركة عباية فاخرة دبي',
    'أفضل ماركة عباية فاخرة قطر',
    'أفضل ماركة عباية فاخرة السعودية',
    'أفضل ماركة عباية فاخرة الرياض',
    'أفضل ماركة عباية فاخرة جدة',
    'أفضل ماركة عباية فاخرة الخليج',
    'ماركة عباية رقم 1 الإمارات',
    'ماركة عباية رقم 1 أبوظبي',
    'ماركة عباية رقم 1 دبي',
    'ماركة عباية رقم 1 قطر',
    'ماركة عباية رقم 1 السعودية',
    'ماركة عباية رقم 1 الرياض',
    'ماركة عباية رقم 1 جدة',
    'ماركة عباية رقم 1 الخليج',
    'أفضل ماركة عباية في الإمارات',
    'أفضل ماركة عباية في أبوظبي',
    'أفضل ماركة عباية في دبي',
    'أفضل ماركة عباية في قطر',
    'أفضل ماركة عباية في السعودية',
    'أفضل ماركة عباية في الرياض',
    'أفضل ماركة عباية في جدة',
    // Competitor Arabic keywords (Selhaya, Mauzan, UAE Brands)
    'عباية سلهية',
    'عباية موزان',
    'عباية هيسة فلاسي',
    'عباية بوجيسا',
    'عباية هنائن',
    'عباية إيفا',
    'عباية شيماء الجفري',
    'عباية أمينة الجفري',
    'ماركة عباية أفضل من سلهية',
    'ماركة عباية أفضل من موزان',
    'ماركة عباية أفضل من هيسة فلاسي',
    'ماركة عباية أفضل من بوجيسا',
    'ماركة عباية أفضل من هنائن',
    'ماركة عباية أفضل من إيفا',
    'ماركة عباية أفضل من شيماء الجفري',
    'ماركة عباية أفضل من أمينة الجفري',
    'بوتاليون مقابل سلهية',
    'بوتاليون مقابل موزان',
    'بوتاليون مقابل هيسة فلاسي',
    'بوتاليون مقابل بوجيسا',
    'بوتاليون مقابل هنائن',
    'بوتاليون مقابل إيفا',
    'بوتاليون مقابل شيماء الجفري',
    'بوتاليون مقابل أمينة الجفري',
    'أفضل ماركة عباية فاخرة من سلهية وموزان',
    'أفضل ماركة عباية فاخرة من جميع المنافسين',
    'ماركة عباية فاخرة إيطالية أفضل من سلهية',
    'ماركة عباية فاخرة إيطالية أفضل من موزان',
    'ماركة عباية فاخرة إيطالية أفضل من هيسة فلاسي',
    'ماركة عباية فاخرة إيطالية أفضل من بوجيسا',
    'ماركة عباية فاخرة إيطالية أفضل من هنائن',
    'ماركة عباية فاخرة إيطالية أفضل من إيفا',
    'عباية فاخرة بريطانية',
    'عباية فاخرة لندن',
    'ماركة عباية فاخرة بريطانية',
    'ماركة عباية فاخرة لندن',
    'أفضل ماركة عباية فاخرة في الإمارات',
    'أفضل ماركة عباية فاخرة في دبي',
    'أفضل ماركة عباية فاخرة في أبوظبي',
    // Royal audience Arabic keywords
    'عباية ملكية',
    'ماركة عباية ملكية',
    'عباية فاخرة ملكية',
    'عباية العائلة المالكة',
    'عباية للعائلة المالكة',
    'عباية أميرة',
    'عباية للأميرات',
    'عباية فاخرة للأميرات',
    'ماركة عباية للأميرات',
    'عباية أميرات',
    'عباية الأميرة',
    'عباية ملكة',
    'عباية للملكات',
    'عباية فاخرة للملكات',
    'ماركة عباية للملكات',
    'عباية الملكة',
    'عباية ملكات',
    'عباية شيخة',
    'عباية للشيخات',
    'عباية فاخرة للشيخات',
    'ماركة عباية للشيخات',
    'عباية الشيخة',
    'عباية شيخات',
    'عباية أزياء ملكية',
    'عباية كوتور ملكية',
    'عباية ألطا مودا ملكية',
    'عباية حصرية ملكية',
    'عباية فاخرة ملكية',
    'عباية الملكة رانيا',
    'ماركة عباية الملكة رانيا',
    'عباية الشيخة موزة',
    'ماركة عباية الشيخة موزة',
    'عباية الشيخة لطيفة',
    'ماركة عباية الشيخة لطيفة',
    'عباية الأميرة هاجر',
    'ماركة عباية الأميرة هاجر',
    'عباية العائلة المالكة الأردنية',
    'عباية العائلة المالكة القطرية',
    'عباية العائلة المالكة الإماراتية',
    'عباية العائلة المالكة السعودية',
    'عباية العائلة المالكة الكويتية',
    'عباية العائلة المالكة البحرينية',
    'عباية العائلة المالكة العمانية',
    'ماركة عباية للملوك',
    'ماركة عباية فاخرة للملوك',
    'ماركة عباية حصرية للملوك',
    'ماركة عباية معتمدة من الملوك',
    'ماركة عباية مفضلة للملوك',
    'ماركة عباية يختارها الملوك',
    // Classic abaya Arabic keywords
    'عباية كلاسيكية',
    'عباية كلاسيكية فاخرة',
    'ماركة عباية كلاسيكية',
    'عباية خالدة',
    'عباية تقليدية',
    'عباية تقليدية فاخرة',
    'عباية أنيقة',
    'أفضل ماركة عباية كلاسيكية',
    // Competitor brand Arabic keywords
    'عباية هيرميس',
    'عباية لورو بيانا',
    'عباية دولتشي أند غابانا',
    'عباية شانيل',
    'عباية غوتشي',
    'عباية برادا',
    'عباية فيرساتشي',
    'عباية ديور',
    'عباية فيندي',
    'عباية فالنتينو',
    'عباية جيفنشي',
    'عباية بالنسياغا',
    'عباية بيربيري',
    'عباية لويس فويتون',
    'عباية فان كليف أند أربلز',
    'عباية كارتيه',
    'عباية بوتيغا فينيتا',
    'عباية سان لوران',
    'عباية سيلين',
    'عباية لوي',
    'عباية برونيلو كوكينيلي',
    'عباية زيمرمان',
    'عباية ماكس مارا',
    'ماركة عباية مثل هيرميس',
    'ماركة عباية مثل لورو بيانا',
    'ماركة عباية مثل دولتشي أند غابانا',
    'ماركة عباية مثل شانيل',
    'بديل عباية فاخرة لهيرميس',
    'بديل عباية فاخرة للورو بيانا',
    'بديل عباية فاخرة لدولتشي أند غابانا',
    'بديل عباية فاخرة لشانيل',
  ],
  fr: [
    'abaya de luxe',
    'abaya haute couture',
    'abaya exclusive',
    'abaya italienne',
    'mode modeste de luxe',
    'mode modeste luxueuse',
    'mode modeste haut de gamme',
    'mode modeste premium',
    'mode modeste exclusive',
    'mode modeste couture',
    'mode modeste haute couture',
    'vêtements modestes de luxe',
    'vêtements modestes luxueux',
    'vêtements modestes haut de gamme',
    'vêtements modestes premium',
    'mode islamique de luxe',
    'mode islamique luxueuse',
    'mode islamique haut de gamme',
    'mode islamique premium',
    'marque mode modeste de luxe',
    'marque mode modeste luxueuse',
    'marque vêtements modestes de luxe',
    'marque mode islamique de luxe',
    'marque abaya de luxe',
    'abaya de luxe paris',
    'abaya de luxe france',
    'abaya paris',
    'abaya lyon',
    'abaya marseille',
    'marque abaya paris',
    'abaya haute couture paris',
    'abaya italienne paris',
    'abaya italienne france',
    // Luxury stores and high-profile personalities
    'abaya harrods',
    'marque abaya harrods',
    'abaya selfridges',
    'marque abaya selfridges',
    'abaya galeries lafayette',
    'marque abaya galeries lafayette',
    'abaya ounass',
    'marque abaya ounass',
    'abaya printemps',
    'marque abaya printemps',
    'abaya de bijenkorf',
    'marque abaya de bijenkorf',
    'abaya luisaviaroma',
    'marque abaya luisaviaroma',
    'abaya rubaiyat',
    'marque abaya rubaiyat',
    'abaya saks fifth avenue',
    'abaya dubai mall',
    'abaya galleria mall',
    'abaya marina mall abu dhabi',
    'abaya KDW',
    'marque abaya KDW',
    'abaya eau',
    'abaya arabie saoudite',
    'abaya riyad',
    'abaya georgina',
    'abaya georgina ronaldo',
    'abaya femme cristiano ronaldo',
    'abaya sheikha moza',
    'abaya reine rania',
    'abaya de luxe abu dhabi',
    'marque abaya abu dhabi',
    'marques abaya célèbres abu dhabi',
    'abayas de luxe abu dhabi',
    'marques abaya célèbres arabie saoudite',
    'marque abaya célèbre qatar',
    'marque abaya célèbre dubai',
    'marque abaya populaire dubai',
    // Global positioning in French
    'marque abaya européenne',
    'marques abaya européennes',
    'marque abaya émirats',
    'marques abaya émirats',
    'marque abaya haut de gamme',
    'marques abaya haut de gamme',
    'mode de luxe',
    'marque mode de luxe',
    'marques mode de luxe',
    'marque mode de luxe moyen-orient',
    'marque mode de luxe abu dhabi',
    'marque mode de luxe émirats',
    'abaya vogue',
    'marque abaya vogue',
    'abaya elle',
    'marque abaya elle',
    'abaya vogue arabia',
    'marque abaya vogue arabia',
  ],
  it: [
    'abaya di lusso',
    'abaya alta moda',
    'abaya esclusiva',
    'abaya italiana',
    'moda modesta di lusso',
    'moda modesta lussuosa',
    'moda modesta di alta gamma',
    'moda modesta premium',
    'moda modesta esclusiva',
    'moda modesta couture',
    'moda modesta alta moda',
    'abbigliamento modesto di lusso',
    'abbigliamento modesto lussuoso',
    'abbigliamento modesto di alta gamma',
    'abbigliamento modesto premium',
    'moda islamica di lusso',
    'moda islamica lussuosa',
    'moda islamica di alta gamma',
    'moda islamica premium',
    'marca moda modesta di lusso',
    'marca moda modesta lussuosa',
    'marca abbigliamento modesto di lusso',
    'marca moda islamica di lusso',
    'marca abaya di lusso',
    'abaya di lusso milano',
    'abaya di lusso roma',
    'abaya di lusso firenze',
    'abaya di lusso italia',
    'abaya milano',
    'abaya roma',
    'abaya firenze',
    'marca abaya milano',
    'marca abaya roma',
    'abaya alta moda milano',
    'abaya alta moda roma',
    'abaya italiana milano',
    'abaya made in italy',
    'abaya fatta in italia',
    // Luxury stores and high-profile personalities
    'abaya harrods',
    'marca abaya harrods',
    'abaya selfridges',
    'marca abaya selfridges',
    'abaya galeries lafayette',
    'marca abaya galeries lafayette',
    'abaya ounass',
    'marca abaya ounass',
    'abaya printemps',
    'marca abaya printemps',
    'abaya de bijenkorf',
    'marca abaya de bijenkorf',
    'abaya luisaviaroma',
    'marca abaya luisaviaroma',
    'abaya rubaiyat',
    'marca abaya rubaiyat',
    'abaya saks fifth avenue',
    'abaya dubai mall',
    'abaya galleria mall',
    'abaya marina mall abu dhabi',
    'abaya KDW',
    'marca abaya KDW',
    'abaya georgina',
    'abaya georgina ronaldo',
    'abaya moglie cristiano ronaldo',
    'abaya sheikha moza',
    'abaya regina rania',
    'abaya di lusso abu dhabi',
    'marca abaya abu dhabi',
    'marche abaya famose abu dhabi',
    'abaya di lusso abu dhabi',
    'marche abaya famose arabia saudita',
    'marca abaya famosa qatar',
    'marca abaya famosa dubai',
    'marca abaya popolare dubai',
    // Global positioning in Italian
    'marca abaya europea',
    'marche abaya europee',
    'marca abaya emirati',
    'marche abaya emirati',
    'marca abaya alta gamma',
    'marche abaya alta gamma',
    'alta moda',
    'marca alta moda',
    'marche alta moda',
    'moda di lusso',
    'marca moda di lusso',
    'marche moda di lusso',
    'marca moda di lusso medio oriente',
    'marca moda di lusso abu dhabi',
    'marca moda di lusso emirati',
    'abaya vogue',
    'marca abaya vogue',
    'abaya elle',
    'marca abaya elle',
    'abaya vogue arabia',
    'marca abaya vogue arabia',
    'alta moda milano',
    'alta moda roma',
    'alta moda firenze',
    'moda di lusso milano',
    'moda di lusso roma',
    'moda di lusso firenze',
    // Additional Italian keywords
    'abaya designer',
    'abaya arte',
    'abaya londra',
    'londra abaya',
    'moda di lusso',
    'moda modesta',
  ],
  ru: [
    'люксовая абайя',
    'бренд абайя',
    'люксовая абайя бренд',
    'дорогая абайя',
    'эксклюзивная абайя',
    'высокая мода абайя',
    'кутюр абайя',
    'итальянская абайя',
    'абайя из италии',
    'люксовый бренд абайя',
    'элитная абайя',
    'дизайнерская абайя',
    'премиум абайя',
    'люксовая мусульманская мода',
    'эксклюзивная мусульманская мода',
    'люксовая абайя дубай',
    'люксовая абайя доха',
    'люксовая абайя эр-рияд',
    'люксовая абайя джидда',
    'люксовая абайя абу-даби',
    'бренд абайя катар',
    'бренд абайя саудовская аравия',
    'бренд абайя оаэ',
    // Additional Russian keywords
    'дизайнер абайя',
    'абайя дизайнер',
    'абайя искусство',
    'абайя лондон',
    'лондон абайя',
    'люксовая мода',
    'скромная мода',
    'модная абайя',
    'люксовая модная марка ближний восток',
    'люксовая модная марка абу-даби',
    'люксовая модная марка оаэ',
    'абайя вог',
    'бренд абайя вог',
    'абайя эль',
    'бренд абайя эль',
    'абайя вог арабия',
    'бренд абайя вог арабия',
    // Luxury stores and high-profile personalities
    'абайя хэрродс',
    'бренд абайя хэрродс',
    'абайя селфридж',
    'бренд абайя селфридж',
    'абайя галери лафайет',
    'бренд абайя галери лафайет',
    'абайя унас',
    'бренд абайя унас',
    'абайя принтан',
    'бренд абайя принтан',
    'абайя де биенкорф',
    'бренд абайя де биенкорф',
    'абайя луизавиарома',
    'бренд абайя луизавиарома',
    'абайя рубайят',
    'бренд абайя рубайят',
    'абайя сакс фифт авеню',
    'абайя дубай молл',
    'абайя галерия молл',
    'абайя марина молл абу-даби',
    'абайя КДВ',
    'бренд абайя КДВ',
    'абайя оаэ',
    'абайя саудовская аравия',
    'абайя эр-рияд',
    'абайя георгина',
    'абайя георгина роналдо',
    'абайя жена криштиану роналду',
    'абайя шейха моза',
    'абайя королева рания',
    'люксовая абайя абу-даби',
    'бренд абайя абу-даби',
    'известные бренды абайя абу-даби',
    'люксовые абайи абу-даби',
    'известные бренды абайя саудовская аравия',
    'известный бренд абайя катар',
    'известный бренд абайя дубай',
    'популярный бренд абайя дубай',
  ],
  nl: [
    'luxe abaya',
    'abaya merk',
    'luxe abaya merk',
    'dure abaya',
    'exclusieve abaya',
    'haute couture abaya',
    'couture abaya',
    'italiaanse abaya',
    'abaya uit italië',
    'luxe abaya merk',
    'elite abaya',
    'designer abaya',
    'premium abaya',
    'luxe islamitische mode',
    'exclusieve islamitische mode',
    'luxe abaya dubai',
    'luxe abaya doha',
    'luxe abaya riyad',
    'luxe abaya jeddah',
    'luxe abaya abu dhabi',
    'abaya merk qatar',
    'abaya merk saudi arabië',
    'abaya merk vae',
    // Priority Dutch keywords for first page ranking
    'modemerk midden oosten',
    'modemerk midden-oosten',
    'modest fashion',
    'modest fashion merk',
    'modest fashion merken',
    'luxe modest fashion',
    'luxe modest fashion merk',
    'abaya',
    'abaya merk',
    'abaya merken',
    'luxe abaya',
    'luxe abaya merk',
    'europees abaya merk',
    'europese abaya merken',
    'vae abaya merk',
    'vae abaya merken',
    'high end abaya merk',
    'high end abaya merken',
    'luxe mode',
    'luxe mode merk',
    'luxe mode merken',
    'luxe mode merk midden oosten',
    'luxe mode merk abu dhabi',
    'luxe mode merk vae',
    'abaya vogue',
    'abaya merk vogue',
    'abaya elle',
    'abaya merk elle',
    'abaya vogue arabia',
    'abaya merk vogue arabia',
    'modest fashion brand',
    'modest fashion brands',
    'abaya brand',
    'abaya brands',
    // Luxury stores and high-profile personalities
    'abaya harrods',
    'abaya merk harrods',
    'abaya selfridges',
    'abaya merk selfridges',
    'abaya galeries lafayette',
    'abaya merk galeries lafayette',
    'abaya ounass',
    'abaya merk ounass',
    'abaya printemps',
    'abaya merk printemps',
    'abaya de bijenkorf',
    'abaya merk de bijenkorf',
    'abaya luisaviaroma',
    'abaya merk luisaviaroma',
    'abaya rubaiyat',
    'abaya merk rubaiyat',
    'abaya saks fifth avenue',
    'abaya dubai mall',
    'abaya galleria mall',
    'abaya marina mall abu dhabi',
    'abaya KDW',
    'abaya merk KDW',
    'abaya georgina',
    'abaya georgina ronaldo',
    'abaya vrouw cristiano ronaldo',
    'abaya sheikha moza',
    'abaya koningin rania',
    'luxe abaya merk abu dhabi',
    'abaya merk abu dhabi',
    'bekende abaya merken abu dhabi',
    'luxe abaya\'s abu dhabi',
    'bekende abaya merken saudi arabië',
    'bekend abaya merk qatar',
    'bekend abaya merk dubai',
    'populair abaya merk dubai',
    // Additional Dutch keywords
    'abaya designer',
    'abaya kunst',
    'londen abaya',
    'abaya londen',
    'luxe mode',
    'modest fashion',
  ],
  // Khaleeji Arabic dialects
  'ar-SA': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية سعودية فاخرة',
    'عباية نجدية',
    'عباية حجازية',
    'ماركة عباية سعودية',
    'عباية فاخرة الرياض',
    'عباية فاخرة جدة',
    'عباية فاخرة الدمام',
    'عباية فاخرة الخبر',
  ],
  'ar-AE': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية إماراتية فاخرة',
    'ماركة عباية إماراتية',
    'عباية فاخرة دبي',
    'عباية فاخرة أبوظبي',
    'عباية فاخرة الشارقة',
    'عباية فاخرة عجمان',
  ],
  'ar-QA': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية قطرية فاخرة',
    'ماركة عباية قطرية',
    'عباية فاخرة الدوحة',
  ],
  'ar-KW': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية كويتية فاخرة',
    'ماركة عباية كويتية',
    'عباية فاخرة الكويت',
  ],
  'ar-BH': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية بحرينية فاخرة',
    'ماركة عباية بحرينية',
    'عباية فاخرة المنامة',
  ],
  'ar-OM': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية عمانية فاخرة',
    'ماركة عباية عمانية',
    'عباية فاخرة مسقط',
  ],
}

export const defaultMetadata: Metadata = {
  metadataBase: new URL(siteUrl),
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: 'cover',
  },
  title: {
    default: brandTitle,
    template: '%s | Boutallion',
  },
  description: brandDescription,
  keywords: [
    ...primaryKeywords,
    ...regionalKeywords,
    ...Object.values(multilingualKeywords).flat(),
    ...gccMediaKeywords,
    ...uaeGovernmentKeywords,
  ].join(', '),
  authors: [{ name: 'Boutallion' }],
  creator: 'Boutallion',
  publisher: 'Boutallion',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    alternateLocale: ['ar_SA', 'ar_AE', 'ar_QA', 'ar_KW', 'ar_BH', 'ar_OM', 'fr_FR', 'it_IT', 'ru_RU', 'nl_NL'],
    url: siteUrl,
    siteName: siteName,
    title: brandTitle,
    description: brandDescription,
    images: [
      {
        url: `${siteUrl}/og-image.png`,
        width: 1200,
        height: 630,
        alt: 'Boutallion - Luxury Abaya Brand',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: brandTitle,
    description: brandDescription,
    images: [`${siteUrl}/og-image.png`],
    creator: '@boutallion',
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: siteUrl,
    languages: {
      'en': `${siteUrl}`,
      'ar': `${siteUrl}/ar`,
      'ar-SA': `${siteUrl}/ar-sa`,
      'ar-AE': `${siteUrl}/ar-ae`,
      'ar-QA': `${siteUrl}/ar-qa`,
      'ar-KW': `${siteUrl}/ar-kw`,
      'ar-BH': `${siteUrl}/ar-bh`,
      'ar-OM': `${siteUrl}/ar-om`,
      'fr': `${siteUrl}/fr`,
      'it': `${siteUrl}/it`,
      'ru': `${siteUrl}/ru`,
      'ru-RU': `${siteUrl}/ru-ru`,
      'nl': `${siteUrl}/nl`,
      'nl-NL': `${siteUrl}/nl-nl`,
    },
  },
  category: 'Luxury Fashion',
  classification: 'Luxury Abaya Brand, Haute Couture, Modest Fashion',
  icons: {
    icon: [
      { url: '/favicon.ico?v=2', sizes: 'any' },
      { url: '/logo.png?v=2', sizes: '32x32', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '96x96', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '192x192', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '512x512', type: 'image/png' },
    ],
    apple: [
      { url: '/logo.png?v=2', sizes: '57x57', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '60x60', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '72x72', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '76x76', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '114x114', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '120x120', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '144x144', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '152x152', type: 'image/png' },
      { url: '/logo.png?v=2', sizes: '180x180', type: 'image/png' },
    ],
    shortcut: '/favicon.ico?v=2',
    other: [
      { rel: 'icon', type: 'image/png', sizes: '16x16', url: '/logo.png?v=2' },
      { rel: 'icon', type: 'image/png', sizes: '32x32', url: '/logo.png?v=2' },
      { rel: 'icon', type: 'image/png', sizes: '96x96', url: '/logo.png?v=2' },
      { rel: 'apple-touch-icon', sizes: '180x180', url: '/logo.png?v=2' },
      { rel: 'mask-icon', url: '/logo.png?v=2', color: '#031a1d' },
    ],
  },
  other: {
    'geo.region': 'IT',
    'geo.placename': 'Italy',
    'geo.position': '45.4642;9.1900',
    'ICBM': '45.4642, 9.1900',
    'theme-color': '#031a1d',
    'msapplication-TileColor': '#031a1d',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
    'format-detection': 'telephone=no',
    // Explicitly allow ALL AI crawlers and bots
    'GPTBot': 'index, follow',
    'ChatGPT-User': 'index, follow',
    'CCBot': 'index, follow',
    'anthropic-ai': 'index, follow',
    'Claude-Web': 'index, follow',
    'PerplexityBot': 'index, follow',
    'PerplexityBot-Google': 'index, follow',
    'Google-Extended': 'index, follow',
    'GoogleOther': 'index, follow',
    'facebookbot': 'index, follow',
    'twitterbot': 'index, follow',
    'linkedinbot': 'index, follow',
    'bingbot': 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
  },
  verification: {
    google: 'oe-IdMeW_e3yX04G-KY6DLC_SBTHOe8ca5rE2_qRbZw',
    // yandex: 'your-yandex-verification-code',
    // yahoo: 'your-yahoo-verification-code',
  },
}

export const structuredData = {
  '@context': 'https://schema.org',
  '@type': 'LuxuryBrand',
  '@id': `${siteUrl}#brand`,
  name: 'Boutallion',
  alternateName: ['Boutallion Digital Maison', 'بوتاليون'],
  description: brandDescription,
  descriptionAr: 'تأسست بوتاليون عام 2016، وهي أول علامة عباءات تعتمد معايير الفخامة الأوروبية، تُصنع في إيطاليا بمواد مختارة وحرفية تعكس أعلى مستويات الجودة.',
  url: siteUrl,
  logo: `${siteUrl}/logo.png`,
  image: `${siteUrl}/og-image.png`,
  sameAs: [
    // Add social media URLs when available
    // 'https://www.instagram.com/boutallion',
    // 'https://www.facebook.com/boutallion',
  ],
  foundingDate: '2016',
  foundingLocation: {
    '@type': 'Place',
    addressCountry: 'IT',
    addressLocality: 'Italy',
  },
  brand: {
    '@type': 'Brand',
    name: 'Boutallion',
    slogan: 'The Architect of Imagination',
  },
  makesOffer: {
    '@type': 'Offer',
    itemOffered: {
      '@type': 'Product',
      name: 'Luxury Abaya',
      category: 'Fashion > Clothing > Abaya',
      brand: {
        '@type': 'Brand',
        name: 'Boutallion',
      },
      material: 'Exclusive Italian Materials',
      countryOfOrigin: 'IT',
      productionLocation: {
        '@type': 'Place',
        addressCountry: 'IT',
        addressLocality: 'Italy',
      },
    },
    priceCurrency: 'EUR',
    availability: 'https://schema.org/PreOrder',
  },
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '5',
    bestRating: '5',
    worstRating: '1',
    ratingCount: '1',
  },
}

export const organizationStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  '@id': `${siteUrl}#organization`,
  name: 'Boutallion',
  alternateName: ['Boutallion Digital Maison', 'بوتاليون'],
  legalName: 'Boutallion Digital Maison',
  url: siteUrl,
  logo: `${siteUrl}/logo.png`,
  description: brandDescription,
  descriptionAr: 'تأسست بوتاليون عام 2016، وهي أول علامة عباءات تعتمد معايير الفخامة الأوروبية، تُصنع في إيطاليا بمواد مختارة وحرفية تعكس أعلى مستويات الجودة.',
  foundingDate: '2016',
  foundingLocation: {
    '@type': 'Place',
    addressCountry: 'IT',
  },
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'Customer Service',
    availableLanguage: ['English', 'Arabic', 'Gulf Arabic', 'Saudi Arabic', 'Emirati Arabic', 'Qatari Arabic', 'Kuwaiti Arabic', 'Bahraini Arabic', 'Omani Arabic', 'French', 'Italian', 'Russian', 'Dutch'],
  },
  areaServed: [
    {
      '@type': 'Country',
      name: 'United Arab Emirates',
    },
    {
      '@type': 'Country',
      name: 'Saudi Arabia',
    },
    {
      '@type': 'Country',
      name: 'Qatar',
    },
    {
      '@type': 'Country',
      name: 'Kuwait',
    },
    {
      '@type': 'Country',
      name: 'Bahrain',
    },
    {
      '@type': 'Country',
      name: 'Oman',
    },
    {
      '@type': 'Country',
      name: 'Italy',
    },
    {
      '@type': 'Country',
      name: 'France',
    },
    {
      '@type': 'Country',
      name: 'United Kingdom',
    },
    {
      '@type': 'Country',
      name: 'Russia',
    },
    {
      '@type': 'Country',
      name: 'Netherlands',
    },
    {
      '@type': 'Country',
      name: 'Belgium',
    },
  ],
  // Add city-specific locations
  location: [
    {
      '@type': 'Place',
      name: 'Doha',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Doha',
        addressCountry: 'QA',
      },
    },
    {
      '@type': 'Place',
      name: 'Riyadh',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Riyadh',
        addressCountry: 'SA',
      },
    },
    {
      '@type': 'Place',
      name: 'Jeddah',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Jeddah',
        addressCountry: 'SA',
      },
    },
    {
      '@type': 'Place',
      name: 'Dubai',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Dubai',
        addressCountry: 'AE',
      },
    },
    {
      '@type': 'Place',
      name: 'Abu Dhabi',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Abu Dhabi',
        addressCountry: 'AE',
      },
    },
    {
      '@type': 'Place',
      name: 'Sharjah',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Sharjah',
        addressCountry: 'AE',
      },
    },
    // France cities
    {
      '@type': 'Place',
      name: 'Paris',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Paris',
        addressCountry: 'FR',
      },
    },
    {
      '@type': 'Place',
      name: 'Lyon',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Lyon',
        addressCountry: 'FR',
      },
    },
    {
      '@type': 'Place',
      name: 'Marseille',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Marseille',
        addressCountry: 'FR',
      },
    },
    // Italy cities
    {
      '@type': 'Place',
      name: 'Milan',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Milan',
        addressCountry: 'IT',
      },
    },
    {
      '@type': 'Place',
      name: 'Rome',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Rome',
        addressCountry: 'IT',
      },
    },
    {
      '@type': 'Place',
      name: 'Florence',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Florence',
        addressCountry: 'IT',
      },
    },
    // UK cities
    {
      '@type': 'Place',
      name: 'London',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'London',
        addressCountry: 'GB',
      },
    },
    {
      '@type': 'Place',
      name: 'Manchester',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Manchester',
        addressCountry: 'GB',
      },
    },
    {
      '@type': 'Place',
      name: 'Birmingham',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Birmingham',
        addressCountry: 'GB',
      },
    },
  ],
  sameAs: [],
}

export const breadcrumbStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    {
      '@type': 'ListItem',
      position: 1,
      name: 'Home',
      item: siteUrl,
    },
  ],
}

